// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: team/team.proto

package team

import (
	base "github.com/kiosk404/echoryn/pkg/proto/base"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TeamStatus represents the lifecycle state of a team.
type TeamStatus int32

const (
	TeamStatus_TEAM_STATUS_UNSPECIFIED TeamStatus = 0
	TeamStatus_TEAM_STATUS_CREATING    TeamStatus = 1
	TeamStatus_TEAM_STATUS_ACTIVE      TeamStatus = 2
	TeamStatus_TEAM_STATUS_WORKING     TeamStatus = 3
	TeamStatus_TEAM_STATUS_COMPLETING  TeamStatus = 4
	TeamStatus_TEAM_STATUS_DISSOLVED   TeamStatus = 5
)

// Enum value maps for TeamStatus.
var (
	TeamStatus_name = map[int32]string{
		0: "TEAM_STATUS_UNSPECIFIED",
		1: "TEAM_STATUS_CREATING",
		2: "TEAM_STATUS_ACTIVE",
		3: "TEAM_STATUS_WORKING",
		4: "TEAM_STATUS_COMPLETING",
		5: "TEAM_STATUS_DISSOLVED",
	}
	TeamStatus_value = map[string]int32{
		"TEAM_STATUS_UNSPECIFIED": 0,
		"TEAM_STATUS_CREATING":    1,
		"TEAM_STATUS_ACTIVE":      2,
		"TEAM_STATUS_WORKING":     3,
		"TEAM_STATUS_COMPLETING":  4,
		"TEAM_STATUS_DISSOLVED":   5,
	}
)

func (x TeamStatus) Enum() *TeamStatus {
	p := new(TeamStatus)
	*p = x
	return p
}

func (x TeamStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TeamStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_team_team_proto_enumTypes[0].Descriptor()
}

func (TeamStatus) Type() protoreflect.EnumType {
	return &file_team_team_proto_enumTypes[0]
}

func (x TeamStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TeamStatus.Descriptor instead.
func (TeamStatus) EnumDescriptor() ([]byte, []int) {
	return file_team_team_proto_rawDescGZIP(), []int{0}
}

// TeamMemberStatus represents the state of a team member.
type TeamMemberStatus int32

const (
	TeamMemberStatus_TEAM_MEMBER_STATUS_UNSPECIFIED TeamMemberStatus = 0
	TeamMemberStatus_TEAM_MEMBER_STATUS_IDLE        TeamMemberStatus = 1
	TeamMemberStatus_TEAM_MEMBER_STATUS_RUNNING     TeamMemberStatus = 2
	TeamMemberStatus_TEAM_MEMBER_STATUS_COMPLETED   TeamMemberStatus = 3
	TeamMemberStatus_TEAM_MEMBER_STATUS_FAILED      TeamMemberStatus = 4
)

// Enum value maps for TeamMemberStatus.
var (
	TeamMemberStatus_name = map[int32]string{
		0: "TEAM_MEMBER_STATUS_UNSPECIFIED",
		1: "TEAM_MEMBER_STATUS_IDLE",
		2: "TEAM_MEMBER_STATUS_RUNNING",
		3: "TEAM_MEMBER_STATUS_COMPLETED",
		4: "TEAM_MEMBER_STATUS_FAILED",
	}
	TeamMemberStatus_value = map[string]int32{
		"TEAM_MEMBER_STATUS_UNSPECIFIED": 0,
		"TEAM_MEMBER_STATUS_IDLE":        1,
		"TEAM_MEMBER_STATUS_RUNNING":     2,
		"TEAM_MEMBER_STATUS_COMPLETED":   3,
		"TEAM_MEMBER_STATUS_FAILED":      4,
	}
)

func (x TeamMemberStatus) Enum() *TeamMemberStatus {
	p := new(TeamMemberStatus)
	*p = x
	return p
}

func (x TeamMemberStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TeamMemberStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_team_team_proto_enumTypes[1].Descriptor()
}

func (TeamMemberStatus) Type() protoreflect.EnumType {
	return &file_team_team_proto_enumTypes[1]
}

func (x TeamMemberStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TeamMemberStatus.Descriptor instead.
func (TeamMemberStatus) EnumDescriptor() ([]byte, []int) {
	return file_team_team_proto_rawDescGZIP(), []int{1}
}

// Team represents an instantiated team with members.
type Team struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Id                   string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	TemplateId           string                 `protobuf:"bytes,3,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"` // Source template ID (empty for ad-hoc)
	TemplateVersion      string                 `protobuf:"bytes,4,opt,name=template_version,json=templateVersion,proto3" json:"template_version,omitempty"`
	ParentSessionId      string                 `protobuf:"bytes,5,opt,name=parent_session_id,json=parentSessionId,proto3" json:"parent_session_id,omitempty"`
	ParentRunId          string                 `protobuf:"bytes,6,opt,name=parent_run_id,json=parentRunId,proto3" json:"parent_run_id,omitempty"`
	TaskDescription      string                 `protobuf:"bytes,7,opt,name=task_description,json=taskDescription,proto3" json:"task_description,omitempty"`
	CoordinationStrategy string                 `protobuf:"bytes,8,opt,name=coordination_strategy,json=coordinationStrategy,proto3" json:"coordination_strategy,omitempty"` // parallel, pipeline, debate, leader_directed
	Status               TeamStatus             `protobuf:"varint,9,opt,name=status,proto3,enum=team.TeamStatus" json:"status,omitempty"`
	Members              []*TeamMember          `protobuf:"bytes,10,rep,name=members,proto3" json:"members,omitempty"`
	LeaderId             string                 `protobuf:"bytes,11,opt,name=leader_id,json=leaderId,proto3" json:"leader_id,omitempty"`
	CreatedAt            *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	CompletedAt          *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	Result               *TeamResult            `protobuf:"bytes,15,opt,name=result,proto3" json:"result,omitempty"`
	Metadata             map[string]string      `protobuf:"bytes,16,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Team) Reset() {
	*x = Team{}
	mi := &file_team_team_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Team) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Team) ProtoMessage() {}

func (x *Team) ProtoReflect() protoreflect.Message {
	mi := &file_team_team_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Team.ProtoReflect.Descriptor instead.
func (*Team) Descriptor() ([]byte, []int) {
	return file_team_team_proto_rawDescGZIP(), []int{0}
}

func (x *Team) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Team) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Team) GetTemplateId() string {
	if x != nil {
		return x.TemplateId
	}
	return ""
}

func (x *Team) GetTemplateVersion() string {
	if x != nil {
		return x.TemplateVersion
	}
	return ""
}

func (x *Team) GetParentSessionId() string {
	if x != nil {
		return x.ParentSessionId
	}
	return ""
}

func (x *Team) GetParentRunId() string {
	if x != nil {
		return x.ParentRunId
	}
	return ""
}

func (x *Team) GetTaskDescription() string {
	if x != nil {
		return x.TaskDescription
	}
	return ""
}

func (x *Team) GetCoordinationStrategy() string {
	if x != nil {
		return x.CoordinationStrategy
	}
	return ""
}

func (x *Team) GetStatus() TeamStatus {
	if x != nil {
		return x.Status
	}
	return TeamStatus_TEAM_STATUS_UNSPECIFIED
}

func (x *Team) GetMembers() []*TeamMember {
	if x != nil {
		return x.Members
	}
	return nil
}

func (x *Team) GetLeaderId() string {
	if x != nil {
		return x.LeaderId
	}
	return ""
}

func (x *Team) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Team) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Team) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

func (x *Team) GetResult() *TeamResult {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *Team) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// TeamMember represents a team member bound to a SubAgent session.
type TeamMember struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SpecId           string                 `protobuf:"bytes,2,opt,name=spec_id,json=specId,proto3" json:"spec_id,omitempty"` // MemberSpec ID from template
	SubagentRecordId string                 `protobuf:"bytes,3,opt,name=subagent_record_id,json=subagentRecordId,proto3" json:"subagent_record_id,omitempty"`
	SessionId        string                 `protobuf:"bytes,4,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	AgentId          string                 `protobuf:"bytes,5,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Role             string                 `protobuf:"bytes,6,opt,name=role,proto3" json:"role,omitempty"`
	Label            string                 `protobuf:"bytes,7,opt,name=label,proto3" json:"label,omitempty"`
	Task             string                 `protobuf:"bytes,8,opt,name=task,proto3" json:"task,omitempty"`
	Status           TeamMemberStatus       `protobuf:"varint,9,opt,name=status,proto3,enum=team.TeamMemberStatus" json:"status,omitempty"`
	JoinedAt         *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=joined_at,json=joinedAt,proto3" json:"joined_at,omitempty"`
	CompletedAt      *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	NodeId           string                 `protobuf:"bytes,12,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"` // Golem node ID (if remote)
	Progress         string                 `protobuf:"bytes,13,opt,name=progress,proto3" json:"progress,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TeamMember) Reset() {
	*x = TeamMember{}
	mi := &file_team_team_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TeamMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TeamMember) ProtoMessage() {}

func (x *TeamMember) ProtoReflect() protoreflect.Message {
	mi := &file_team_team_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TeamMember.ProtoReflect.Descriptor instead.
func (*TeamMember) Descriptor() ([]byte, []int) {
	return file_team_team_proto_rawDescGZIP(), []int{1}
}

func (x *TeamMember) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TeamMember) GetSpecId() string {
	if x != nil {
		return x.SpecId
	}
	return ""
}

func (x *TeamMember) GetSubagentRecordId() string {
	if x != nil {
		return x.SubagentRecordId
	}
	return ""
}

func (x *TeamMember) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *TeamMember) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *TeamMember) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *TeamMember) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *TeamMember) GetTask() string {
	if x != nil {
		return x.Task
	}
	return ""
}

func (x *TeamMember) GetStatus() TeamMemberStatus {
	if x != nil {
		return x.Status
	}
	return TeamMemberStatus_TEAM_MEMBER_STATUS_UNSPECIFIED
}

func (x *TeamMember) GetJoinedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.JoinedAt
	}
	return nil
}

func (x *TeamMember) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

func (x *TeamMember) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *TeamMember) GetProgress() string {
	if x != nil {
		return x.Progress
	}
	return ""
}

// TeamResult is the aggregated result from a team.
type TeamResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Summary       string                 `protobuf:"bytes,1,opt,name=summary,proto3" json:"summary,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	MemberOutputs []string               `protobuf:"bytes,3,rep,name=member_outputs,json=memberOutputs,proto3" json:"member_outputs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TeamResult) Reset() {
	*x = TeamResult{}
	mi := &file_team_team_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TeamResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TeamResult) ProtoMessage() {}

func (x *TeamResult) ProtoReflect() protoreflect.Message {
	mi := &file_team_team_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TeamResult.ProtoReflect.Descriptor instead.
func (*TeamResult) Descriptor() ([]byte, []int) {
	return file_team_team_proto_rawDescGZIP(), []int{2}
}

func (x *TeamResult) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *TeamResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TeamResult) GetMemberOutputs() []string {
	if x != nil {
		return x.MemberOutputs
	}
	return nil
}

// TeamTemplate defines a reusable team structure.
type TeamTemplate struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name            string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Version         string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Description     string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	MemberSpecs     []*MemberSpec          `protobuf:"bytes,5,rep,name=member_specs,json=memberSpecs,proto3" json:"member_specs,omitempty"`
	DefaultStrategy string                 `protobuf:"bytes,6,opt,name=default_strategy,json=defaultStrategy,proto3" json:"default_strategy,omitempty"`
	LeaderSpecIndex int32                  `protobuf:"varint,7,opt,name=leader_spec_index,json=leaderSpecIndex,proto3" json:"leader_spec_index,omitempty"`
	SystemPrompt    string                 `protobuf:"bytes,8,opt,name=system_prompt,json=systemPrompt,proto3" json:"system_prompt,omitempty"`
	Tags            []string               `protobuf:"bytes,9,rep,name=tags,proto3" json:"tags,omitempty"`
	CreatedAt       *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt       *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TeamTemplate) Reset() {
	*x = TeamTemplate{}
	mi := &file_team_team_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TeamTemplate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TeamTemplate) ProtoMessage() {}

func (x *TeamTemplate) ProtoReflect() protoreflect.Message {
	mi := &file_team_team_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TeamTemplate.ProtoReflect.Descriptor instead.
func (*TeamTemplate) Descriptor() ([]byte, []int) {
	return file_team_team_proto_rawDescGZIP(), []int{3}
}

func (x *TeamTemplate) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TeamTemplate) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TeamTemplate) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *TeamTemplate) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *TeamTemplate) GetMemberSpecs() []*MemberSpec {
	if x != nil {
		return x.MemberSpecs
	}
	return nil
}

func (x *TeamTemplate) GetDefaultStrategy() string {
	if x != nil {
		return x.DefaultStrategy
	}
	return ""
}

func (x *TeamTemplate) GetLeaderSpecIndex() int32 {
	if x != nil {
		return x.LeaderSpecIndex
	}
	return 0
}

func (x *TeamTemplate) GetSystemPrompt() string {
	if x != nil {
		return x.SystemPrompt
	}
	return ""
}

func (x *TeamTemplate) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *TeamTemplate) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *TeamTemplate) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// MemberSpec defines a role within a team template.
type MemberSpec struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Role             string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	DisplayName      string                 `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Description      string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	RecommendedModel string                 `protobuf:"bytes,5,opt,name=recommended_model,json=recommendedModel,proto3" json:"recommended_model,omitempty"`
	IsLeader         bool                   `protobuf:"varint,6,opt,name=is_leader,json=isLeader,proto3" json:"is_leader,omitempty"`
	CanCommunicate   bool                   `protobuf:"varint,7,opt,name=can_communicate,json=canCommunicate,proto3" json:"can_communicate,omitempty"`
	SystemPrompt     string                 `protobuf:"bytes,8,opt,name=system_prompt,json=systemPrompt,proto3" json:"system_prompt,omitempty"`
	DefaultTask      string                 `protobuf:"bytes,9,opt,name=default_task,json=defaultTask,proto3" json:"default_task,omitempty"`
	Skills           []string               `protobuf:"bytes,10,rep,name=skills,proto3" json:"skills,omitempty"`
	MinCount         int32                  `protobuf:"varint,11,opt,name=min_count,json=minCount,proto3" json:"min_count,omitempty"`
	MaxCount         int32                  `protobuf:"varint,12,opt,name=max_count,json=maxCount,proto3" json:"max_count,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *MemberSpec) Reset() {
	*x = MemberSpec{}
	mi := &file_team_team_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemberSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemberSpec) ProtoMessage() {}

func (x *MemberSpec) ProtoReflect() protoreflect.Message {
	mi := &file_team_team_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemberSpec.ProtoReflect.Descriptor instead.
func (*MemberSpec) Descriptor() ([]byte, []int) {
	return file_team_team_proto_rawDescGZIP(), []int{4}
}

func (x *MemberSpec) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MemberSpec) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *MemberSpec) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *MemberSpec) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *MemberSpec) GetRecommendedModel() string {
	if x != nil {
		return x.RecommendedModel
	}
	return ""
}

func (x *MemberSpec) GetIsLeader() bool {
	if x != nil {
		return x.IsLeader
	}
	return false
}

func (x *MemberSpec) GetCanCommunicate() bool {
	if x != nil {
		return x.CanCommunicate
	}
	return false
}

func (x *MemberSpec) GetSystemPrompt() string {
	if x != nil {
		return x.SystemPrompt
	}
	return ""
}

func (x *MemberSpec) GetDefaultTask() string {
	if x != nil {
		return x.DefaultTask
	}
	return ""
}

func (x *MemberSpec) GetSkills() []string {
	if x != nil {
		return x.Skills
	}
	return nil
}

func (x *MemberSpec) GetMinCount() int32 {
	if x != nil {
		return x.MinCount
	}
	return 0
}

func (x *MemberSpec) GetMaxCount() int32 {
	if x != nil {
		return x.MaxCount
	}
	return 0
}

// CreateTeamRequest supports two modes:
//  1. Template-based: provide template_id
//  2. Ad-hoc: provide name + strategy directly
type CreateTeamRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Template-based creation fields.
	TemplateId       string `protobuf:"bytes,1,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`                   // Template ID for template-based creation
	TaskDescription  string `protobuf:"bytes,2,opt,name=task_description,json=taskDescription,proto3" json:"task_description,omitempty"`    // Task description for the team
	StrategyOverride string `protobuf:"bytes,3,opt,name=strategy_override,json=strategyOverride,proto3" json:"strategy_override,omitempty"` // Override template's default strategy
	// Member overrides (keyed by MemberSpec ID).
	MemberOverrides map[string]*MemberOverride `protobuf:"bytes,4,rep,name=member_overrides,json=memberOverrides,proto3" json:"member_overrides,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Ad-hoc creation fields (used when template_id is empty).
	Name     string `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`         // Team name
	Strategy string `protobuf:"bytes,6,opt,name=strategy,proto3" json:"strategy,omitempty"` // Coordination strategy
	// Context fields (populated by the server).
	ParentSessionId string `protobuf:"bytes,7,opt,name=parent_session_id,json=parentSessionId,proto3" json:"parent_session_id,omitempty"`
	ParentRunId     string `protobuf:"bytes,8,opt,name=parent_run_id,json=parentRunId,proto3" json:"parent_run_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateTeamRequest) Reset() {
	*x = CreateTeamRequest{}
	mi := &file_team_team_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTeamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTeamRequest) ProtoMessage() {}

func (x *CreateTeamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_team_team_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTeamRequest.ProtoReflect.Descriptor instead.
func (*CreateTeamRequest) Descriptor() ([]byte, []int) {
	return file_team_team_proto_rawDescGZIP(), []int{5}
}

func (x *CreateTeamRequest) GetTemplateId() string {
	if x != nil {
		return x.TemplateId
	}
	return ""
}

func (x *CreateTeamRequest) GetTaskDescription() string {
	if x != nil {
		return x.TaskDescription
	}
	return ""
}

func (x *CreateTeamRequest) GetStrategyOverride() string {
	if x != nil {
		return x.StrategyOverride
	}
	return ""
}

func (x *CreateTeamRequest) GetMemberOverrides() map[string]*MemberOverride {
	if x != nil {
		return x.MemberOverrides
	}
	return nil
}

func (x *CreateTeamRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateTeamRequest) GetStrategy() string {
	if x != nil {
		return x.Strategy
	}
	return ""
}

func (x *CreateTeamRequest) GetParentSessionId() string {
	if x != nil {
		return x.ParentSessionId
	}
	return ""
}

func (x *CreateTeamRequest) GetParentRunId() string {
	if x != nil {
		return x.ParentRunId
	}
	return ""
}

// MemberOverride allows customizing a template member spec during instantiation.
type MemberOverride struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Model         string                 `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	Task          string                 `protobuf:"bytes,3,opt,name=task,proto3" json:"task,omitempty"`
	Disabled      bool                   `protobuf:"varint,4,opt,name=disabled,proto3" json:"disabled,omitempty"` // Skip this member spec
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemberOverride) Reset() {
	*x = MemberOverride{}
	mi := &file_team_team_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemberOverride) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemberOverride) ProtoMessage() {}

func (x *MemberOverride) ProtoReflect() protoreflect.Message {
	mi := &file_team_team_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemberOverride.ProtoReflect.Descriptor instead.
func (*MemberOverride) Descriptor() ([]byte, []int) {
	return file_team_team_proto_rawDescGZIP(), []int{6}
}

func (x *MemberOverride) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *MemberOverride) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *MemberOverride) GetTask() string {
	if x != nil {
		return x.Task
	}
	return ""
}

func (x *MemberOverride) GetDisabled() bool {
	if x != nil {
		return x.Disabled
	}
	return false
}

type CreateTeamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Team          *Team                  `protobuf:"bytes,1,opt,name=team,proto3" json:"team,omitempty"`
	BaseResp      *base.BaseResp         `protobuf:"bytes,255,opt,name=base_resp,json=baseResp,proto3" json:"base_resp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTeamResponse) Reset() {
	*x = CreateTeamResponse{}
	mi := &file_team_team_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTeamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTeamResponse) ProtoMessage() {}

func (x *CreateTeamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_team_team_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTeamResponse.ProtoReflect.Descriptor instead.
func (*CreateTeamResponse) Descriptor() ([]byte, []int) {
	return file_team_team_proto_rawDescGZIP(), []int{7}
}

func (x *CreateTeamResponse) GetTeam() *Team {
	if x != nil {
		return x.Team
	}
	return nil
}

func (x *CreateTeamResponse) GetBaseResp() *base.BaseResp {
	if x != nil {
		return x.BaseResp
	}
	return nil
}

type GetTeamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TeamId        string                 `protobuf:"bytes,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTeamRequest) Reset() {
	*x = GetTeamRequest{}
	mi := &file_team_team_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTeamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTeamRequest) ProtoMessage() {}

func (x *GetTeamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_team_team_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTeamRequest.ProtoReflect.Descriptor instead.
func (*GetTeamRequest) Descriptor() ([]byte, []int) {
	return file_team_team_proto_rawDescGZIP(), []int{8}
}

func (x *GetTeamRequest) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

type GetTeamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Team          *Team                  `protobuf:"bytes,1,opt,name=team,proto3" json:"team,omitempty"`
	BaseResp      *base.BaseResp         `protobuf:"bytes,255,opt,name=base_resp,json=baseResp,proto3" json:"base_resp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTeamResponse) Reset() {
	*x = GetTeamResponse{}
	mi := &file_team_team_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTeamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTeamResponse) ProtoMessage() {}

func (x *GetTeamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_team_team_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTeamResponse.ProtoReflect.Descriptor instead.
func (*GetTeamResponse) Descriptor() ([]byte, []int) {
	return file_team_team_proto_rawDescGZIP(), []int{9}
}

func (x *GetTeamResponse) GetTeam() *Team {
	if x != nil {
		return x.Team
	}
	return nil
}

func (x *GetTeamResponse) GetBaseResp() *base.BaseResp {
	if x != nil {
		return x.BaseResp
	}
	return nil
}

type ListTeamsRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ParentSessionId string                 `protobuf:"bytes,1,opt,name=parent_session_id,json=parentSessionId,proto3" json:"parent_session_id,omitempty"` // Optional: filter by parent session
	PageSize        int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken       string                 `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ListTeamsRequest) Reset() {
	*x = ListTeamsRequest{}
	mi := &file_team_team_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTeamsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTeamsRequest) ProtoMessage() {}

func (x *ListTeamsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_team_team_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTeamsRequest.ProtoReflect.Descriptor instead.
func (*ListTeamsRequest) Descriptor() ([]byte, []int) {
	return file_team_team_proto_rawDescGZIP(), []int{10}
}

func (x *ListTeamsRequest) GetParentSessionId() string {
	if x != nil {
		return x.ParentSessionId
	}
	return ""
}

func (x *ListTeamsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListTeamsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListTeamsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Teams         []*Team                `protobuf:"bytes,1,rep,name=teams,proto3" json:"teams,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	TotalCount    int32                  `protobuf:"varint,3,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	BaseResp      *base.BaseResp         `protobuf:"bytes,255,opt,name=base_resp,json=baseResp,proto3" json:"base_resp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTeamsResponse) Reset() {
	*x = ListTeamsResponse{}
	mi := &file_team_team_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTeamsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTeamsResponse) ProtoMessage() {}

func (x *ListTeamsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_team_team_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTeamsResponse.ProtoReflect.Descriptor instead.
func (*ListTeamsResponse) Descriptor() ([]byte, []int) {
	return file_team_team_proto_rawDescGZIP(), []int{11}
}

func (x *ListTeamsResponse) GetTeams() []*Team {
	if x != nil {
		return x.Teams
	}
	return nil
}

func (x *ListTeamsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

func (x *ListTeamsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ListTeamsResponse) GetBaseResp() *base.BaseResp {
	if x != nil {
		return x.BaseResp
	}
	return nil
}

type DissolveTeamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TeamId        string                 `protobuf:"bytes,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DissolveTeamRequest) Reset() {
	*x = DissolveTeamRequest{}
	mi := &file_team_team_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DissolveTeamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DissolveTeamRequest) ProtoMessage() {}

func (x *DissolveTeamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_team_team_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DissolveTeamRequest.ProtoReflect.Descriptor instead.
func (*DissolveTeamRequest) Descriptor() ([]byte, []int) {
	return file_team_team_proto_rawDescGZIP(), []int{12}
}

func (x *DissolveTeamRequest) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

type DissolveTeamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	BaseResp      *base.BaseResp         `protobuf:"bytes,255,opt,name=base_resp,json=baseResp,proto3" json:"base_resp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DissolveTeamResponse) Reset() {
	*x = DissolveTeamResponse{}
	mi := &file_team_team_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DissolveTeamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DissolveTeamResponse) ProtoMessage() {}

func (x *DissolveTeamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_team_team_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DissolveTeamResponse.ProtoReflect.Descriptor instead.
func (*DissolveTeamResponse) Descriptor() ([]byte, []int) {
	return file_team_team_proto_rawDescGZIP(), []int{13}
}

func (x *DissolveTeamResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DissolveTeamResponse) GetBaseResp() *base.BaseResp {
	if x != nil {
		return x.BaseResp
	}
	return nil
}

type AddMemberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TeamId        string                 `protobuf:"bytes,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	Role          string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	Label         string                 `protobuf:"bytes,3,opt,name=label,proto3" json:"label,omitempty"`
	Task          string                 `protobuf:"bytes,4,opt,name=task,proto3" json:"task,omitempty"`
	Model         string                 `protobuf:"bytes,5,opt,name=model,proto3" json:"model,omitempty"`                    // Optional model override
	AgentId       string                 `protobuf:"bytes,6,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"` // Optional agent ID
	IsLeader      bool                   `protobuf:"varint,7,opt,name=is_leader,json=isLeader,proto3" json:"is_leader,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddMemberRequest) Reset() {
	*x = AddMemberRequest{}
	mi := &file_team_team_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddMemberRequest) ProtoMessage() {}

func (x *AddMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_team_team_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddMemberRequest.ProtoReflect.Descriptor instead.
func (*AddMemberRequest) Descriptor() ([]byte, []int) {
	return file_team_team_proto_rawDescGZIP(), []int{14}
}

func (x *AddMemberRequest) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

func (x *AddMemberRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *AddMemberRequest) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *AddMemberRequest) GetTask() string {
	if x != nil {
		return x.Task
	}
	return ""
}

func (x *AddMemberRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *AddMemberRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AddMemberRequest) GetIsLeader() bool {
	if x != nil {
		return x.IsLeader
	}
	return false
}

type AddMemberResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Member        *TeamMember            `protobuf:"bytes,1,opt,name=member,proto3" json:"member,omitempty"`
	BaseResp      *base.BaseResp         `protobuf:"bytes,255,opt,name=base_resp,json=baseResp,proto3" json:"base_resp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddMemberResponse) Reset() {
	*x = AddMemberResponse{}
	mi := &file_team_team_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddMemberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddMemberResponse) ProtoMessage() {}

func (x *AddMemberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_team_team_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddMemberResponse.ProtoReflect.Descriptor instead.
func (*AddMemberResponse) Descriptor() ([]byte, []int) {
	return file_team_team_proto_rawDescGZIP(), []int{15}
}

func (x *AddMemberResponse) GetMember() *TeamMember {
	if x != nil {
		return x.Member
	}
	return nil
}

func (x *AddMemberResponse) GetBaseResp() *base.BaseResp {
	if x != nil {
		return x.BaseResp
	}
	return nil
}

type RemoveMemberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TeamId        string                 `protobuf:"bytes,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	MemberId      string                 `protobuf:"bytes,2,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveMemberRequest) Reset() {
	*x = RemoveMemberRequest{}
	mi := &file_team_team_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveMemberRequest) ProtoMessage() {}

func (x *RemoveMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_team_team_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveMemberRequest.ProtoReflect.Descriptor instead.
func (*RemoveMemberRequest) Descriptor() ([]byte, []int) {
	return file_team_team_proto_rawDescGZIP(), []int{16}
}

func (x *RemoveMemberRequest) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

func (x *RemoveMemberRequest) GetMemberId() string {
	if x != nil {
		return x.MemberId
	}
	return ""
}

type RemoveMemberResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	BaseResp      *base.BaseResp         `protobuf:"bytes,255,opt,name=base_resp,json=baseResp,proto3" json:"base_resp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveMemberResponse) Reset() {
	*x = RemoveMemberResponse{}
	mi := &file_team_team_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveMemberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveMemberResponse) ProtoMessage() {}

func (x *RemoveMemberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_team_team_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveMemberResponse.ProtoReflect.Descriptor instead.
func (*RemoveMemberResponse) Descriptor() ([]byte, []int) {
	return file_team_team_proto_rawDescGZIP(), []int{17}
}

func (x *RemoveMemberResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RemoveMemberResponse) GetBaseResp() *base.BaseResp {
	if x != nil {
		return x.BaseResp
	}
	return nil
}

// SendTeamMessageRequest supports both point-to-point and broadcast messages.
type SendTeamMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TeamId        string                 `protobuf:"bytes,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	FromSessionId string                 `protobuf:"bytes,2,opt,name=from_session_id,json=fromSessionId,proto3" json:"from_session_id,omitempty"`
	ToSessionId   string                 `protobuf:"bytes,3,opt,name=to_session_id,json=toSessionId,proto3" json:"to_session_id,omitempty"` // Empty for broadcast
	IsBroadcast   bool                   `protobuf:"varint,4,opt,name=is_broadcast,json=isBroadcast,proto3" json:"is_broadcast,omitempty"`  // v1.4: explicit broadcast flag
	MessageType   string                 `protobuf:"bytes,5,opt,name=message_type,json=messageType,proto3" json:"message_type,omitempty"`   // chat, task, result, steer, status, shutdown
	Content       string                 `protobuf:"bytes,6,opt,name=content,proto3" json:"content,omitempty"`
	Priority      int32                  `protobuf:"varint,7,opt,name=priority,proto3" json:"priority,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendTeamMessageRequest) Reset() {
	*x = SendTeamMessageRequest{}
	mi := &file_team_team_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendTeamMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendTeamMessageRequest) ProtoMessage() {}

func (x *SendTeamMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_team_team_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendTeamMessageRequest.ProtoReflect.Descriptor instead.
func (*SendTeamMessageRequest) Descriptor() ([]byte, []int) {
	return file_team_team_proto_rawDescGZIP(), []int{18}
}

func (x *SendTeamMessageRequest) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

func (x *SendTeamMessageRequest) GetFromSessionId() string {
	if x != nil {
		return x.FromSessionId
	}
	return ""
}

func (x *SendTeamMessageRequest) GetToSessionId() string {
	if x != nil {
		return x.ToSessionId
	}
	return ""
}

func (x *SendTeamMessageRequest) GetIsBroadcast() bool {
	if x != nil {
		return x.IsBroadcast
	}
	return false
}

func (x *SendTeamMessageRequest) GetMessageType() string {
	if x != nil {
		return x.MessageType
	}
	return ""
}

func (x *SendTeamMessageRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *SendTeamMessageRequest) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

type SendTeamMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	MessageId     string                 `protobuf:"bytes,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	BaseResp      *base.BaseResp         `protobuf:"bytes,255,opt,name=base_resp,json=baseResp,proto3" json:"base_resp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendTeamMessageResponse) Reset() {
	*x = SendTeamMessageResponse{}
	mi := &file_team_team_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendTeamMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendTeamMessageResponse) ProtoMessage() {}

func (x *SendTeamMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_team_team_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendTeamMessageResponse.ProtoReflect.Descriptor instead.
func (*SendTeamMessageResponse) Descriptor() ([]byte, []int) {
	return file_team_team_proto_rawDescGZIP(), []int{19}
}

func (x *SendTeamMessageResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SendTeamMessageResponse) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *SendTeamMessageResponse) GetBaseResp() *base.BaseResp {
	if x != nil {
		return x.BaseResp
	}
	return nil
}

type ListTemplatesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional filters.
	Tags          []string `protobuf:"bytes,1,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTemplatesRequest) Reset() {
	*x = ListTemplatesRequest{}
	mi := &file_team_team_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTemplatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTemplatesRequest) ProtoMessage() {}

func (x *ListTemplatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_team_team_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTemplatesRequest.ProtoReflect.Descriptor instead.
func (*ListTemplatesRequest) Descriptor() ([]byte, []int) {
	return file_team_team_proto_rawDescGZIP(), []int{20}
}

func (x *ListTemplatesRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type ListTemplatesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Templates     []*TeamTemplate        `protobuf:"bytes,1,rep,name=templates,proto3" json:"templates,omitempty"`
	BaseResp      *base.BaseResp         `protobuf:"bytes,255,opt,name=base_resp,json=baseResp,proto3" json:"base_resp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTemplatesResponse) Reset() {
	*x = ListTemplatesResponse{}
	mi := &file_team_team_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTemplatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTemplatesResponse) ProtoMessage() {}

func (x *ListTemplatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_team_team_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTemplatesResponse.ProtoReflect.Descriptor instead.
func (*ListTemplatesResponse) Descriptor() ([]byte, []int) {
	return file_team_team_proto_rawDescGZIP(), []int{21}
}

func (x *ListTemplatesResponse) GetTemplates() []*TeamTemplate {
	if x != nil {
		return x.Templates
	}
	return nil
}

func (x *ListTemplatesResponse) GetBaseResp() *base.BaseResp {
	if x != nil {
		return x.BaseResp
	}
	return nil
}

var File_team_team_proto protoreflect.FileDescriptor

const file_team_team_proto_rawDesc = "" +
	"\n" +
	"\x0fteam/team.proto\x12\x04team\x1a\x0fbase/base.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xeb\x05\n" +
	"\x04Team\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1f\n" +
	"\vtemplate_id\x18\x03 \x01(\tR\n" +
	"templateId\x12)\n" +
	"\x10template_version\x18\x04 \x01(\tR\x0ftemplateVersion\x12*\n" +
	"\x11parent_session_id\x18\x05 \x01(\tR\x0fparentSessionId\x12\"\n" +
	"\rparent_run_id\x18\x06 \x01(\tR\vparentRunId\x12)\n" +
	"\x10task_description\x18\a \x01(\tR\x0ftaskDescription\x123\n" +
	"\x15coordination_strategy\x18\b \x01(\tR\x14coordinationStrategy\x12(\n" +
	"\x06status\x18\t \x01(\x0e2\x10.team.TeamStatusR\x06status\x12*\n" +
	"\amembers\x18\n" +
	" \x03(\v2\x10.team.TeamMemberR\amembers\x12\x1b\n" +
	"\tleader_id\x18\v \x01(\tR\bleaderId\x129\n" +
	"\n" +
	"created_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12=\n" +
	"\fcompleted_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt\x12(\n" +
	"\x06result\x18\x0f \x01(\v2\x10.team.TeamResultR\x06result\x124\n" +
	"\bmetadata\x18\x10 \x03(\v2\x18.team.Team.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb8\x03\n" +
	"\n" +
	"TeamMember\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\aspec_id\x18\x02 \x01(\tR\x06specId\x12,\n" +
	"\x12subagent_record_id\x18\x03 \x01(\tR\x10subagentRecordId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x04 \x01(\tR\tsessionId\x12\x19\n" +
	"\bagent_id\x18\x05 \x01(\tR\aagentId\x12\x12\n" +
	"\x04role\x18\x06 \x01(\tR\x04role\x12\x14\n" +
	"\x05label\x18\a \x01(\tR\x05label\x12\x12\n" +
	"\x04task\x18\b \x01(\tR\x04task\x12.\n" +
	"\x06status\x18\t \x01(\x0e2\x16.team.TeamMemberStatusR\x06status\x127\n" +
	"\tjoined_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\bjoinedAt\x12=\n" +
	"\fcompleted_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt\x12\x17\n" +
	"\anode_id\x18\f \x01(\tR\x06nodeId\x12\x1a\n" +
	"\bprogress\x18\r \x01(\tR\bprogress\"g\n" +
	"\n" +
	"TeamResult\x12\x18\n" +
	"\asummary\x18\x01 \x01(\tR\asummary\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12%\n" +
	"\x0emember_outputs\x18\x03 \x03(\tR\rmemberOutputs\"\xa9\x03\n" +
	"\fTeamTemplate\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x123\n" +
	"\fmember_specs\x18\x05 \x03(\v2\x10.team.MemberSpecR\vmemberSpecs\x12)\n" +
	"\x10default_strategy\x18\x06 \x01(\tR\x0fdefaultStrategy\x12*\n" +
	"\x11leader_spec_index\x18\a \x01(\x05R\x0fleaderSpecIndex\x12#\n" +
	"\rsystem_prompt\x18\b \x01(\tR\fsystemPrompt\x12\x12\n" +
	"\x04tags\x18\t \x03(\tR\x04tags\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x82\x03\n" +
	"\n" +
	"MemberSpec\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\x12!\n" +
	"\fdisplay_name\x18\x03 \x01(\tR\vdisplayName\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12+\n" +
	"\x11recommended_model\x18\x05 \x01(\tR\x10recommendedModel\x12\x1b\n" +
	"\tis_leader\x18\x06 \x01(\bR\bisLeader\x12'\n" +
	"\x0fcan_communicate\x18\a \x01(\bR\x0ecanCommunicate\x12#\n" +
	"\rsystem_prompt\x18\b \x01(\tR\fsystemPrompt\x12!\n" +
	"\fdefault_task\x18\t \x01(\tR\vdefaultTask\x12\x16\n" +
	"\x06skills\x18\n" +
	" \x03(\tR\x06skills\x12\x1b\n" +
	"\tmin_count\x18\v \x01(\x05R\bminCount\x12\x1b\n" +
	"\tmax_count\x18\f \x01(\x05R\bmaxCount\"\xbf\x03\n" +
	"\x11CreateTeamRequest\x12\x1f\n" +
	"\vtemplate_id\x18\x01 \x01(\tR\n" +
	"templateId\x12)\n" +
	"\x10task_description\x18\x02 \x01(\tR\x0ftaskDescription\x12+\n" +
	"\x11strategy_override\x18\x03 \x01(\tR\x10strategyOverride\x12W\n" +
	"\x10member_overrides\x18\x04 \x03(\v2,.team.CreateTeamRequest.MemberOverridesEntryR\x0fmemberOverrides\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\x12\x1a\n" +
	"\bstrategy\x18\x06 \x01(\tR\bstrategy\x12*\n" +
	"\x11parent_session_id\x18\a \x01(\tR\x0fparentSessionId\x12\"\n" +
	"\rparent_run_id\x18\b \x01(\tR\vparentRunId\x1aX\n" +
	"\x14MemberOverridesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12*\n" +
	"\x05value\x18\x02 \x01(\v2\x14.team.MemberOverrideR\x05value:\x028\x01\"q\n" +
	"\x0eMemberOverride\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\x12\x12\n" +
	"\x04task\x18\x03 \x01(\tR\x04task\x12\x1a\n" +
	"\bdisabled\x18\x04 \x01(\bR\bdisabled\"b\n" +
	"\x12CreateTeamResponse\x12\x1e\n" +
	"\x04team\x18\x01 \x01(\v2\n" +
	".team.TeamR\x04team\x12,\n" +
	"\tbase_resp\x18\xff\x01 \x01(\v2\x0e.base.BaseRespR\bbaseResp\")\n" +
	"\x0eGetTeamRequest\x12\x17\n" +
	"\ateam_id\x18\x01 \x01(\tR\x06teamId\"_\n" +
	"\x0fGetTeamResponse\x12\x1e\n" +
	"\x04team\x18\x01 \x01(\v2\n" +
	".team.TeamR\x04team\x12,\n" +
	"\tbase_resp\x18\xff\x01 \x01(\v2\x0e.base.BaseRespR\bbaseResp\"z\n" +
	"\x10ListTeamsRequest\x12*\n" +
	"\x11parent_session_id\x18\x01 \x01(\tR\x0fparentSessionId\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageToken\"\xac\x01\n" +
	"\x11ListTeamsResponse\x12 \n" +
	"\x05teams\x18\x01 \x03(\v2\n" +
	".team.TeamR\x05teams\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\x12\x1f\n" +
	"\vtotal_count\x18\x03 \x01(\x05R\n" +
	"totalCount\x12,\n" +
	"\tbase_resp\x18\xff\x01 \x01(\v2\x0e.base.BaseRespR\bbaseResp\".\n" +
	"\x13DissolveTeamRequest\x12\x17\n" +
	"\ateam_id\x18\x01 \x01(\tR\x06teamId\"^\n" +
	"\x14DissolveTeamResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12,\n" +
	"\tbase_resp\x18\xff\x01 \x01(\v2\x0e.base.BaseRespR\bbaseResp\"\xb7\x01\n" +
	"\x10AddMemberRequest\x12\x17\n" +
	"\ateam_id\x18\x01 \x01(\tR\x06teamId\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\x12\x14\n" +
	"\x05label\x18\x03 \x01(\tR\x05label\x12\x12\n" +
	"\x04task\x18\x04 \x01(\tR\x04task\x12\x14\n" +
	"\x05model\x18\x05 \x01(\tR\x05model\x12\x19\n" +
	"\bagent_id\x18\x06 \x01(\tR\aagentId\x12\x1b\n" +
	"\tis_leader\x18\a \x01(\bR\bisLeader\"k\n" +
	"\x11AddMemberResponse\x12(\n" +
	"\x06member\x18\x01 \x01(\v2\x10.team.TeamMemberR\x06member\x12,\n" +
	"\tbase_resp\x18\xff\x01 \x01(\v2\x0e.base.BaseRespR\bbaseResp\"K\n" +
	"\x13RemoveMemberRequest\x12\x17\n" +
	"\ateam_id\x18\x01 \x01(\tR\x06teamId\x12\x1b\n" +
	"\tmember_id\x18\x02 \x01(\tR\bmemberId\"^\n" +
	"\x14RemoveMemberResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12,\n" +
	"\tbase_resp\x18\xff\x01 \x01(\v2\x0e.base.BaseRespR\bbaseResp\"\xf9\x01\n" +
	"\x16SendTeamMessageRequest\x12\x17\n" +
	"\ateam_id\x18\x01 \x01(\tR\x06teamId\x12&\n" +
	"\x0ffrom_session_id\x18\x02 \x01(\tR\rfromSessionId\x12\"\n" +
	"\rto_session_id\x18\x03 \x01(\tR\vtoSessionId\x12!\n" +
	"\fis_broadcast\x18\x04 \x01(\bR\visBroadcast\x12!\n" +
	"\fmessage_type\x18\x05 \x01(\tR\vmessageType\x12\x18\n" +
	"\acontent\x18\x06 \x01(\tR\acontent\x12\x1a\n" +
	"\bpriority\x18\a \x01(\x05R\bpriority\"\x80\x01\n" +
	"\x17SendTeamMessageResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\tR\tmessageId\x12,\n" +
	"\tbase_resp\x18\xff\x01 \x01(\v2\x0e.base.BaseRespR\bbaseResp\"*\n" +
	"\x14ListTemplatesRequest\x12\x12\n" +
	"\x04tags\x18\x01 \x03(\tR\x04tags\"w\n" +
	"\x15ListTemplatesResponse\x120\n" +
	"\ttemplates\x18\x01 \x03(\v2\x12.team.TeamTemplateR\ttemplates\x12,\n" +
	"\tbase_resp\x18\xff\x01 \x01(\v2\x0e.base.BaseRespR\bbaseResp*\xab\x01\n" +
	"\n" +
	"TeamStatus\x12\x1b\n" +
	"\x17TEAM_STATUS_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14TEAM_STATUS_CREATING\x10\x01\x12\x16\n" +
	"\x12TEAM_STATUS_ACTIVE\x10\x02\x12\x17\n" +
	"\x13TEAM_STATUS_WORKING\x10\x03\x12\x1a\n" +
	"\x16TEAM_STATUS_COMPLETING\x10\x04\x12\x19\n" +
	"\x15TEAM_STATUS_DISSOLVED\x10\x05*\xb4\x01\n" +
	"\x10TeamMemberStatus\x12\"\n" +
	"\x1eTEAM_MEMBER_STATUS_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17TEAM_MEMBER_STATUS_IDLE\x10\x01\x12\x1e\n" +
	"\x1aTEAM_MEMBER_STATUS_RUNNING\x10\x02\x12 \n" +
	"\x1cTEAM_MEMBER_STATUS_COMPLETED\x10\x03\x12\x1d\n" +
	"\x19TEAM_MEMBER_STATUS_FAILED\x10\x042\xaa\x04\n" +
	"\vTeamService\x12?\n" +
	"\n" +
	"CreateTeam\x12\x17.team.CreateTeamRequest\x1a\x18.team.CreateTeamResponse\x126\n" +
	"\aGetTeam\x12\x14.team.GetTeamRequest\x1a\x15.team.GetTeamResponse\x12<\n" +
	"\tListTeams\x12\x16.team.ListTeamsRequest\x1a\x17.team.ListTeamsResponse\x12E\n" +
	"\fDissolveTeam\x12\x19.team.DissolveTeamRequest\x1a\x1a.team.DissolveTeamResponse\x12<\n" +
	"\tAddMember\x12\x16.team.AddMemberRequest\x1a\x17.team.AddMemberResponse\x12E\n" +
	"\fRemoveMember\x12\x19.team.RemoveMemberRequest\x1a\x1a.team.RemoveMemberResponse\x12N\n" +
	"\x0fSendTeamMessage\x12\x1c.team.SendTeamMessageRequest\x1a\x1d.team.SendTeamMessageResponse\x12H\n" +
	"\rListTemplates\x12\x1a.team.ListTemplatesRequest\x1a\x1b.team.ListTemplatesResponseB,Z*github.com/kiosk404/echoryn/pkg/proto/teamb\x06proto3"

var (
	file_team_team_proto_rawDescOnce sync.Once
	file_team_team_proto_rawDescData []byte
)

func file_team_team_proto_rawDescGZIP() []byte {
	file_team_team_proto_rawDescOnce.Do(func() {
		file_team_team_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_team_team_proto_rawDesc), len(file_team_team_proto_rawDesc)))
	})
	return file_team_team_proto_rawDescData
}

var file_team_team_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_team_team_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_team_team_proto_goTypes = []any{
	(TeamStatus)(0),                 // 0: team.TeamStatus
	(TeamMemberStatus)(0),           // 1: team.TeamMemberStatus
	(*Team)(nil),                    // 2: team.Team
	(*TeamMember)(nil),              // 3: team.TeamMember
	(*TeamResult)(nil),              // 4: team.TeamResult
	(*TeamTemplate)(nil),            // 5: team.TeamTemplate
	(*MemberSpec)(nil),              // 6: team.MemberSpec
	(*CreateTeamRequest)(nil),       // 7: team.CreateTeamRequest
	(*MemberOverride)(nil),          // 8: team.MemberOverride
	(*CreateTeamResponse)(nil),      // 9: team.CreateTeamResponse
	(*GetTeamRequest)(nil),          // 10: team.GetTeamRequest
	(*GetTeamResponse)(nil),         // 11: team.GetTeamResponse
	(*ListTeamsRequest)(nil),        // 12: team.ListTeamsRequest
	(*ListTeamsResponse)(nil),       // 13: team.ListTeamsResponse
	(*DissolveTeamRequest)(nil),     // 14: team.DissolveTeamRequest
	(*DissolveTeamResponse)(nil),    // 15: team.DissolveTeamResponse
	(*AddMemberRequest)(nil),        // 16: team.AddMemberRequest
	(*AddMemberResponse)(nil),       // 17: team.AddMemberResponse
	(*RemoveMemberRequest)(nil),     // 18: team.RemoveMemberRequest
	(*RemoveMemberResponse)(nil),    // 19: team.RemoveMemberResponse
	(*SendTeamMessageRequest)(nil),  // 20: team.SendTeamMessageRequest
	(*SendTeamMessageResponse)(nil), // 21: team.SendTeamMessageResponse
	(*ListTemplatesRequest)(nil),    // 22: team.ListTemplatesRequest
	(*ListTemplatesResponse)(nil),   // 23: team.ListTemplatesResponse
	nil,                             // 24: team.Team.MetadataEntry
	nil,                             // 25: team.CreateTeamRequest.MemberOverridesEntry
	(*timestamppb.Timestamp)(nil),   // 26: google.protobuf.Timestamp
	(*base.BaseResp)(nil),           // 27: base.BaseResp
}
var file_team_team_proto_depIdxs = []int32{
	0,  // 0: team.Team.status:type_name -> team.TeamStatus
	3,  // 1: team.Team.members:type_name -> team.TeamMember
	26, // 2: team.Team.created_at:type_name -> google.protobuf.Timestamp
	26, // 3: team.Team.updated_at:type_name -> google.protobuf.Timestamp
	26, // 4: team.Team.completed_at:type_name -> google.protobuf.Timestamp
	4,  // 5: team.Team.result:type_name -> team.TeamResult
	24, // 6: team.Team.metadata:type_name -> team.Team.MetadataEntry
	1,  // 7: team.TeamMember.status:type_name -> team.TeamMemberStatus
	26, // 8: team.TeamMember.joined_at:type_name -> google.protobuf.Timestamp
	26, // 9: team.TeamMember.completed_at:type_name -> google.protobuf.Timestamp
	6,  // 10: team.TeamTemplate.member_specs:type_name -> team.MemberSpec
	26, // 11: team.TeamTemplate.created_at:type_name -> google.protobuf.Timestamp
	26, // 12: team.TeamTemplate.updated_at:type_name -> google.protobuf.Timestamp
	25, // 13: team.CreateTeamRequest.member_overrides:type_name -> team.CreateTeamRequest.MemberOverridesEntry
	2,  // 14: team.CreateTeamResponse.team:type_name -> team.Team
	27, // 15: team.CreateTeamResponse.base_resp:type_name -> base.BaseResp
	2,  // 16: team.GetTeamResponse.team:type_name -> team.Team
	27, // 17: team.GetTeamResponse.base_resp:type_name -> base.BaseResp
	2,  // 18: team.ListTeamsResponse.teams:type_name -> team.Team
	27, // 19: team.ListTeamsResponse.base_resp:type_name -> base.BaseResp
	27, // 20: team.DissolveTeamResponse.base_resp:type_name -> base.BaseResp
	3,  // 21: team.AddMemberResponse.member:type_name -> team.TeamMember
	27, // 22: team.AddMemberResponse.base_resp:type_name -> base.BaseResp
	27, // 23: team.RemoveMemberResponse.base_resp:type_name -> base.BaseResp
	27, // 24: team.SendTeamMessageResponse.base_resp:type_name -> base.BaseResp
	5,  // 25: team.ListTemplatesResponse.templates:type_name -> team.TeamTemplate
	27, // 26: team.ListTemplatesResponse.base_resp:type_name -> base.BaseResp
	8,  // 27: team.CreateTeamRequest.MemberOverridesEntry.value:type_name -> team.MemberOverride
	7,  // 28: team.TeamService.CreateTeam:input_type -> team.CreateTeamRequest
	10, // 29: team.TeamService.GetTeam:input_type -> team.GetTeamRequest
	12, // 30: team.TeamService.ListTeams:input_type -> team.ListTeamsRequest
	14, // 31: team.TeamService.DissolveTeam:input_type -> team.DissolveTeamRequest
	16, // 32: team.TeamService.AddMember:input_type -> team.AddMemberRequest
	18, // 33: team.TeamService.RemoveMember:input_type -> team.RemoveMemberRequest
	20, // 34: team.TeamService.SendTeamMessage:input_type -> team.SendTeamMessageRequest
	22, // 35: team.TeamService.ListTemplates:input_type -> team.ListTemplatesRequest
	9,  // 36: team.TeamService.CreateTeam:output_type -> team.CreateTeamResponse
	11, // 37: team.TeamService.GetTeam:output_type -> team.GetTeamResponse
	13, // 38: team.TeamService.ListTeams:output_type -> team.ListTeamsResponse
	15, // 39: team.TeamService.DissolveTeam:output_type -> team.DissolveTeamResponse
	17, // 40: team.TeamService.AddMember:output_type -> team.AddMemberResponse
	19, // 41: team.TeamService.RemoveMember:output_type -> team.RemoveMemberResponse
	21, // 42: team.TeamService.SendTeamMessage:output_type -> team.SendTeamMessageResponse
	23, // 43: team.TeamService.ListTemplates:output_type -> team.ListTemplatesResponse
	36, // [36:44] is the sub-list for method output_type
	28, // [28:36] is the sub-list for method input_type
	28, // [28:28] is the sub-list for extension type_name
	28, // [28:28] is the sub-list for extension extendee
	0,  // [0:28] is the sub-list for field type_name
}

func init() { file_team_team_proto_init() }
func file_team_team_proto_init() {
	if File_team_team_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_team_team_proto_rawDesc), len(file_team_team_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_team_team_proto_goTypes,
		DependencyIndexes: file_team_team_proto_depIdxs,
		EnumInfos:         file_team_team_proto_enumTypes,
		MessageInfos:      file_team_team_proto_msgTypes,
	}.Build()
	File_team_team_proto = out.File
	file_team_team_proto_goTypes = nil
	file_team_team_proto_depIdxs = nil
}
