// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: golem/golem.proto

package golem

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// NodeStatus 节点状态枚举
type NodeStatus int32

const (
	NodeStatus_NODE_STATUS_UNSPECIFIED NodeStatus = 0
	NodeStatus_NODE_STATUS_ONLINE      NodeStatus = 1 // 在线可调度
	NodeStatus_NODE_STATUS_OFFLINE     NodeStatus = 2 // 离线
	NodeStatus_NODE_STATUS_DRAINING    NodeStatus = 3 // 排水中 (不接受新任务, 等待现有任务完成)
	NodeStatus_NODE_STATUS_CORDONED    NodeStatus = 4 // 已隔离 (手动标记不可调度)
)

// Enum value maps for NodeStatus.
var (
	NodeStatus_name = map[int32]string{
		0: "NODE_STATUS_UNSPECIFIED",
		1: "NODE_STATUS_ONLINE",
		2: "NODE_STATUS_OFFLINE",
		3: "NODE_STATUS_DRAINING",
		4: "NODE_STATUS_CORDONED",
	}
	NodeStatus_value = map[string]int32{
		"NODE_STATUS_UNSPECIFIED": 0,
		"NODE_STATUS_ONLINE":      1,
		"NODE_STATUS_OFFLINE":     2,
		"NODE_STATUS_DRAINING":    3,
		"NODE_STATUS_CORDONED":    4,
	}
)

func (x NodeStatus) Enum() *NodeStatus {
	p := new(NodeStatus)
	*p = x
	return p
}

func (x NodeStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NodeStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_golem_golem_proto_enumTypes[0].Descriptor()
}

func (NodeStatus) Type() protoreflect.EnumType {
	return &file_golem_golem_proto_enumTypes[0]
}

func (x NodeStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NodeStatus.Descriptor instead.
func (NodeStatus) EnumDescriptor() ([]byte, []int) {
	return file_golem_golem_proto_rawDescGZIP(), []int{0}
}

// TaskStatus 任务状态枚举
type TaskStatus int32

const (
	TaskStatus_TASK_STATUS_UNSPECIFIED TaskStatus = 0
	TaskStatus_TASK_STATUS_PENDING     TaskStatus = 1 // 等待调度
	TaskStatus_TASK_STATUS_ASSIGNED    TaskStatus = 2 // 已分配到节点
	TaskStatus_TASK_STATUS_RUNNING     TaskStatus = 3 // 正在执行
	TaskStatus_TASK_STATUS_COMPLETED   TaskStatus = 4 // 成功完成
	TaskStatus_TASK_STATUS_FAILED      TaskStatus = 5 // 失败
	TaskStatus_TASK_STATUS_CANCELLED   TaskStatus = 6 // 已取消
	TaskStatus_TASK_STATUS_TIMED_OUT   TaskStatus = 7 // 超时
)

// Enum value maps for TaskStatus.
var (
	TaskStatus_name = map[int32]string{
		0: "TASK_STATUS_UNSPECIFIED",
		1: "TASK_STATUS_PENDING",
		2: "TASK_STATUS_ASSIGNED",
		3: "TASK_STATUS_RUNNING",
		4: "TASK_STATUS_COMPLETED",
		5: "TASK_STATUS_FAILED",
		6: "TASK_STATUS_CANCELLED",
		7: "TASK_STATUS_TIMED_OUT",
	}
	TaskStatus_value = map[string]int32{
		"TASK_STATUS_UNSPECIFIED": 0,
		"TASK_STATUS_PENDING":     1,
		"TASK_STATUS_ASSIGNED":    2,
		"TASK_STATUS_RUNNING":     3,
		"TASK_STATUS_COMPLETED":   4,
		"TASK_STATUS_FAILED":      5,
		"TASK_STATUS_CANCELLED":   6,
		"TASK_STATUS_TIMED_OUT":   7,
	}
)

func (x TaskStatus) Enum() *TaskStatus {
	p := new(TaskStatus)
	*p = x
	return p
}

func (x TaskStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_golem_golem_proto_enumTypes[1].Descriptor()
}

func (TaskStatus) Type() protoreflect.EnumType {
	return &file_golem_golem_proto_enumTypes[1]
}

func (x TaskStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskStatus.Descriptor instead.
func (TaskStatus) EnumDescriptor() ([]byte, []int) {
	return file_golem_golem_proto_rawDescGZIP(), []int{1}
}

// TaskPriority 任务优先级
type TaskPriority int32

const (
	TaskPriority_TASK_PRIORITY_UNSPECIFIED TaskPriority = 0
	TaskPriority_TASK_PRIORITY_LOW         TaskPriority = 1
	TaskPriority_TASK_PRIORITY_NORMAL      TaskPriority = 5
	TaskPriority_TASK_PRIORITY_HIGH        TaskPriority = 8
	TaskPriority_TASK_PRIORITY_CRITICAL    TaskPriority = 10
)

// Enum value maps for TaskPriority.
var (
	TaskPriority_name = map[int32]string{
		0:  "TASK_PRIORITY_UNSPECIFIED",
		1:  "TASK_PRIORITY_LOW",
		5:  "TASK_PRIORITY_NORMAL",
		8:  "TASK_PRIORITY_HIGH",
		10: "TASK_PRIORITY_CRITICAL",
	}
	TaskPriority_value = map[string]int32{
		"TASK_PRIORITY_UNSPECIFIED": 0,
		"TASK_PRIORITY_LOW":         1,
		"TASK_PRIORITY_NORMAL":      5,
		"TASK_PRIORITY_HIGH":        8,
		"TASK_PRIORITY_CRITICAL":    10,
	}
)

func (x TaskPriority) Enum() *TaskPriority {
	p := new(TaskPriority)
	*p = x
	return p
}

func (x TaskPriority) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskPriority) Descriptor() protoreflect.EnumDescriptor {
	return file_golem_golem_proto_enumTypes[2].Descriptor()
}

func (TaskPriority) Type() protoreflect.EnumType {
	return &file_golem_golem_proto_enumTypes[2]
}

func (x TaskPriority) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskPriority.Descriptor instead.
func (TaskPriority) EnumDescriptor() ([]byte, []int) {
	return file_golem_golem_proto_rawDescGZIP(), []int{2}
}

// HeartbeatAction 心跳响应中 Hivemind 可下发的控制指令
type HeartbeatAction int32

const (
	HeartbeatAction_HEARTBEAT_ACTION_UNSPECIFIED HeartbeatAction = 0
	HeartbeatAction_HEARTBEAT_ACTION_NONE        HeartbeatAction = 1 // 无操作
	HeartbeatAction_HEARTBEAT_ACTION_DRAIN       HeartbeatAction = 2 // 开始排水
	HeartbeatAction_HEARTBEAT_ACTION_SHUTDOWN    HeartbeatAction = 3 // 要求关闭
)

// Enum value maps for HeartbeatAction.
var (
	HeartbeatAction_name = map[int32]string{
		0: "HEARTBEAT_ACTION_UNSPECIFIED",
		1: "HEARTBEAT_ACTION_NONE",
		2: "HEARTBEAT_ACTION_DRAIN",
		3: "HEARTBEAT_ACTION_SHUTDOWN",
	}
	HeartbeatAction_value = map[string]int32{
		"HEARTBEAT_ACTION_UNSPECIFIED": 0,
		"HEARTBEAT_ACTION_NONE":        1,
		"HEARTBEAT_ACTION_DRAIN":       2,
		"HEARTBEAT_ACTION_SHUTDOWN":    3,
	}
)

func (x HeartbeatAction) Enum() *HeartbeatAction {
	p := new(HeartbeatAction)
	*p = x
	return p
}

func (x HeartbeatAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HeartbeatAction) Descriptor() protoreflect.EnumDescriptor {
	return file_golem_golem_proto_enumTypes[3].Descriptor()
}

func (HeartbeatAction) Type() protoreflect.EnumType {
	return &file_golem_golem_proto_enumTypes[3]
}

func (x HeartbeatAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HeartbeatAction.Descriptor instead.
func (HeartbeatAction) EnumDescriptor() ([]byte, []int) {
	return file_golem_golem_proto_rawDescGZIP(), []int{3}
}

// Capability 节点能力描述
type Capability struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`               // 能力名称 (e.g. "browser_automation", "code_execution")
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`         // 能力版本
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"` // 能力描述
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Capability) Reset() {
	*x = Capability{}
	mi := &file_golem_golem_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Capability) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Capability) ProtoMessage() {}

func (x *Capability) ProtoReflect() protoreflect.Message {
	mi := &file_golem_golem_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Capability.ProtoReflect.Descriptor instead.
func (*Capability) Descriptor() ([]byte, []int) {
	return file_golem_golem_proto_rawDescGZIP(), []int{0}
}

func (x *Capability) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Capability) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Capability) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// SystemInfo 节点系统信息 (静态, 注册时上报)
type SystemInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CpuCores      int32                  `protobuf:"varint,1,opt,name=cpu_cores,json=cpuCores,proto3" json:"cpu_cores,omitempty"`         // CPU 核心数
	MemoryMb      int64                  `protobuf:"varint,2,opt,name=memory_mb,json=memoryMb,proto3" json:"memory_mb,omitempty"`         // 总内存 (MB)
	DiskFreeMb    int64                  `protobuf:"varint,3,opt,name=disk_free_mb,json=diskFreeMb,proto3" json:"disk_free_mb,omitempty"` // 可用磁盘空间 (MB)
	Os            string                 `protobuf:"bytes,4,opt,name=os,proto3" json:"os,omitempty"`                                      // 操作系统 (e.g. "linux", "darwin")
	Arch          string                 `protobuf:"bytes,5,opt,name=arch,proto3" json:"arch,omitempty"`                                  // 架构 (e.g. "amd64", "arm64")
	Hostname      string                 `protobuf:"bytes,6,opt,name=hostname,proto3" json:"hostname,omitempty"`                          // 主机名
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SystemInfo) Reset() {
	*x = SystemInfo{}
	mi := &file_golem_golem_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemInfo) ProtoMessage() {}

func (x *SystemInfo) ProtoReflect() protoreflect.Message {
	mi := &file_golem_golem_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemInfo.ProtoReflect.Descriptor instead.
func (*SystemInfo) Descriptor() ([]byte, []int) {
	return file_golem_golem_proto_rawDescGZIP(), []int{1}
}

func (x *SystemInfo) GetCpuCores() int32 {
	if x != nil {
		return x.CpuCores
	}
	return 0
}

func (x *SystemInfo) GetMemoryMb() int64 {
	if x != nil {
		return x.MemoryMb
	}
	return 0
}

func (x *SystemInfo) GetDiskFreeMb() int64 {
	if x != nil {
		return x.DiskFreeMb
	}
	return 0
}

func (x *SystemInfo) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *SystemInfo) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *SystemInfo) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

// NodeInfo 节点注册信息 (静态 + 半静态)
type NodeInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                                                                   // 节点唯一 ID
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                                                                               // 节点可读名称
	Address       string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`                                                                         // 节点地址 (ip:port)
	Status        NodeStatus             `protobuf:"varint,4,opt,name=status,proto3,enum=golem.NodeStatus" json:"status,omitempty"`                                                    // 节点状态
	SystemInfo    *SystemInfo            `protobuf:"bytes,5,opt,name=system_info,json=systemInfo,proto3" json:"system_info,omitempty"`                                                 // 系统信息
	Capabilities  []*Capability          `protobuf:"bytes,6,rep,name=capabilities,proto3" json:"capabilities,omitempty"`                                                               // 已注册的能力列表
	Labels        map[string]string      `protobuf:"bytes,7,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 用户自定义标签
	Version       string                 `protobuf:"bytes,8,opt,name=version,proto3" json:"version,omitempty"`                                                                         // Golem 版本号
	RegisteredAt  *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=registered_at,json=registeredAt,proto3" json:"registered_at,omitempty"`
	LastSeenAt    *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=last_seen_at,json=lastSeenAt,proto3" json:"last_seen_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeInfo) Reset() {
	*x = NodeInfo{}
	mi := &file_golem_golem_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeInfo) ProtoMessage() {}

func (x *NodeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_golem_golem_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeInfo.ProtoReflect.Descriptor instead.
func (*NodeInfo) Descriptor() ([]byte, []int) {
	return file_golem_golem_proto_rawDescGZIP(), []int{2}
}

func (x *NodeInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *NodeInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NodeInfo) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *NodeInfo) GetStatus() NodeStatus {
	if x != nil {
		return x.Status
	}
	return NodeStatus_NODE_STATUS_UNSPECIFIED
}

func (x *NodeInfo) GetSystemInfo() *SystemInfo {
	if x != nil {
		return x.SystemInfo
	}
	return nil
}

func (x *NodeInfo) GetCapabilities() []*Capability {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *NodeInfo) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *NodeInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *NodeInfo) GetRegisteredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RegisteredAt
	}
	return nil
}

func (x *NodeInfo) GetLastSeenAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSeenAt
	}
	return nil
}

// NodeLoadInfo 节点负载信息 (动态, 心跳上报)
type NodeLoadInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CpuPercent    float64                `protobuf:"fixed64,1,opt,name=cpu_percent,json=cpuPercent,proto3" json:"cpu_percent,omitempty"`
	MemoryPercent float64                `protobuf:"fixed64,2,opt,name=memory_percent,json=memoryPercent,proto3" json:"memory_percent,omitempty"`
	DiskFreeMb    int64                  `protobuf:"varint,3,opt,name=disk_free_mb,json=diskFreeMb,proto3" json:"disk_free_mb,omitempty"`
	ActiveTasks   int32                  `protobuf:"varint,4,opt,name=active_tasks,json=activeTasks,proto3" json:"active_tasks,omitempty"`
	QueuedTasks   int32                  `protobuf:"varint,5,opt,name=queued_tasks,json=queuedTasks,proto3" json:"queued_tasks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeLoadInfo) Reset() {
	*x = NodeLoadInfo{}
	mi := &file_golem_golem_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeLoadInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeLoadInfo) ProtoMessage() {}

func (x *NodeLoadInfo) ProtoReflect() protoreflect.Message {
	mi := &file_golem_golem_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeLoadInfo.ProtoReflect.Descriptor instead.
func (*NodeLoadInfo) Descriptor() ([]byte, []int) {
	return file_golem_golem_proto_rawDescGZIP(), []int{3}
}

func (x *NodeLoadInfo) GetCpuPercent() float64 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}

func (x *NodeLoadInfo) GetMemoryPercent() float64 {
	if x != nil {
		return x.MemoryPercent
	}
	return 0
}

func (x *NodeLoadInfo) GetDiskFreeMb() int64 {
	if x != nil {
		return x.DiskFreeMb
	}
	return 0
}

func (x *NodeLoadInfo) GetActiveTasks() int32 {
	if x != nil {
		return x.ActiveTasks
	}
	return 0
}

func (x *NodeLoadInfo) GetQueuedTasks() int32 {
	if x != nil {
		return x.QueuedTasks
	}
	return 0
}

// Task 任务定义
type Task struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	SkillName      string                 `protobuf:"bytes,3,opt,name=skill_name,json=skillName,proto3" json:"skill_name,omitempty"`
	Payload        []byte                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"` // JSON-encoded skill parameters
	Status         TaskStatus             `protobuf:"varint,5,opt,name=status,proto3,enum=golem.TaskStatus" json:"status,omitempty"`
	Priority       TaskPriority           `protobuf:"varint,6,opt,name=priority,proto3,enum=golem.TaskPriority" json:"priority,omitempty"`
	AssignedNodeId string                 `protobuf:"bytes,7,opt,name=assigned_node_id,json=assignedNodeId,proto3" json:"assigned_node_id,omitempty"`
	SessionId      string                 `protobuf:"bytes,8,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	AgentId        string                 `protobuf:"bytes,9,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Result         []byte                 `protobuf:"bytes,10,opt,name=result,proto3" json:"result,omitempty"`
	Error          string                 `protobuf:"bytes,11,opt,name=error,proto3" json:"error,omitempty"`
	Timeout        *durationpb.Duration   `protobuf:"bytes,12,opt,name=timeout,proto3" json:"timeout,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	StartedAt      *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	CompletedAt    *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	Metadata       map[string]string      `protobuf:"bytes,16,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_golem_golem_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_golem_golem_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_golem_golem_proto_rawDescGZIP(), []int{4}
}

func (x *Task) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Task) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Task) GetSkillName() string {
	if x != nil {
		return x.SkillName
	}
	return ""
}

func (x *Task) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Task) GetStatus() TaskStatus {
	if x != nil {
		return x.Status
	}
	return TaskStatus_TASK_STATUS_UNSPECIFIED
}

func (x *Task) GetPriority() TaskPriority {
	if x != nil {
		return x.Priority
	}
	return TaskPriority_TASK_PRIORITY_UNSPECIFIED
}

func (x *Task) GetAssignedNodeId() string {
	if x != nil {
		return x.AssignedNodeId
	}
	return ""
}

func (x *Task) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *Task) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *Task) GetResult() []byte {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *Task) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *Task) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

func (x *Task) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Task) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *Task) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

func (x *Task) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// TaskProgress 任务进度上报
type TaskProgress struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TaskId          string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	ProgressPercent float64                `protobuf:"fixed64,2,opt,name=progress_percent,json=progressPercent,proto3" json:"progress_percent,omitempty"`
	StatusMessage   string                 `protobuf:"bytes,3,opt,name=status_message,json=statusMessage,proto3" json:"status_message,omitempty"`
	PartialResult   []byte                 `protobuf:"bytes,4,opt,name=partial_result,json=partialResult,proto3" json:"partial_result,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TaskProgress) Reset() {
	*x = TaskProgress{}
	mi := &file_golem_golem_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskProgress) ProtoMessage() {}

func (x *TaskProgress) ProtoReflect() protoreflect.Message {
	mi := &file_golem_golem_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskProgress.ProtoReflect.Descriptor instead.
func (*TaskProgress) Descriptor() ([]byte, []int) {
	return file_golem_golem_proto_rawDescGZIP(), []int{5}
}

func (x *TaskProgress) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskProgress) GetProgressPercent() float64 {
	if x != nil {
		return x.ProgressPercent
	}
	return 0
}

func (x *TaskProgress) GetStatusMessage() string {
	if x != nil {
		return x.StatusMessage
	}
	return ""
}

func (x *TaskProgress) GetPartialResult() []byte {
	if x != nil {
		return x.PartialResult
	}
	return nil
}

// TaskResult 任务最终结果
type TaskResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Output        []byte                 `protobuf:"bytes,3,opt,name=output,proto3" json:"output,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskResult) Reset() {
	*x = TaskResult{}
	mi := &file_golem_golem_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResult) ProtoMessage() {}

func (x *TaskResult) ProtoReflect() protoreflect.Message {
	mi := &file_golem_golem_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResult.ProtoReflect.Descriptor instead.
func (*TaskResult) Descriptor() ([]byte, []int) {
	return file_golem_golem_proto_rawDescGZIP(), []int{6}
}

func (x *TaskResult) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TaskResult) GetOutput() []byte {
	if x != nil {
		return x.Output
	}
	return nil
}

func (x *TaskResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type BaseResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusMessage string                 `protobuf:"bytes,1,opt,name=status_message,json=statusMessage,proto3" json:"status_message,omitempty"`
	StatusCode    int32                  `protobuf:"varint,2,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaseResp) Reset() {
	*x = BaseResp{}
	mi := &file_golem_golem_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseResp) ProtoMessage() {}

func (x *BaseResp) ProtoReflect() protoreflect.Message {
	mi := &file_golem_golem_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseResp.ProtoReflect.Descriptor instead.
func (*BaseResp) Descriptor() ([]byte, []int) {
	return file_golem_golem_proto_rawDescGZIP(), []int{7}
}

func (x *BaseResp) GetStatusMessage() string {
	if x != nil {
		return x.StatusMessage
	}
	return ""
}

func (x *BaseResp) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JoinToken     string                 `protobuf:"bytes,1,opt,name=join_token,json=joinToken,proto3" json:"join_token,omitempty"`
	NodeInfo      *NodeInfo              `protobuf:"bytes,2,opt,name=node_info,json=nodeInfo,proto3" json:"node_info,omitempty"`
	LoadInfo      *NodeLoadInfo          `protobuf:"bytes,3,opt,name=load_info,json=loadInfo,proto3" json:"load_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_golem_golem_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_golem_golem_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_golem_golem_proto_rawDescGZIP(), []int{8}
}

func (x *RegisterRequest) GetJoinToken() string {
	if x != nil {
		return x.JoinToken
	}
	return ""
}

func (x *RegisterRequest) GetNodeInfo() *NodeInfo {
	if x != nil {
		return x.NodeInfo
	}
	return nil
}

func (x *RegisterRequest) GetLoadInfo() *NodeLoadInfo {
	if x != nil {
		return x.LoadInfo
	}
	return nil
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	NodeId        string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	RejectReason  string                 `protobuf:"bytes,3,opt,name=reject_reason,json=rejectReason,proto3" json:"reject_reason,omitempty"`
	BaseResp      *BaseResp              `protobuf:"bytes,255,opt,name=base_resp,json=baseResp,proto3" json:"base_resp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_golem_golem_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_golem_golem_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_golem_golem_proto_rawDescGZIP(), []int{9}
}

func (x *RegisterResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *RegisterResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *RegisterResponse) GetRejectReason() string {
	if x != nil {
		return x.RejectReason
	}
	return ""
}

func (x *RegisterResponse) GetBaseResp() *BaseResp {
	if x != nil {
		return x.BaseResp
	}
	return nil
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	LoadInfo      *NodeLoadInfo          `protobuf:"bytes,2,opt,name=load_info,json=loadInfo,proto3" json:"load_info,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_golem_golem_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_golem_golem_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_golem_golem_proto_rawDescGZIP(), []int{10}
}

func (x *HeartbeatRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *HeartbeatRequest) GetLoadInfo() *NodeLoadInfo {
	if x != nil {
		return x.LoadInfo
	}
	return nil
}

func (x *HeartbeatRequest) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Acknowledged  bool                   `protobuf:"varint,1,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	Action        HeartbeatAction        `protobuf:"varint,2,opt,name=action,proto3,enum=golem.HeartbeatAction" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_golem_golem_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_golem_golem_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_golem_golem_proto_rawDescGZIP(), []int{11}
}

func (x *HeartbeatResponse) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

func (x *HeartbeatResponse) GetAction() HeartbeatAction {
	if x != nil {
		return x.Action
	}
	return HeartbeatAction_HEARTBEAT_ACTION_UNSPECIFIED
}

type DeregisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeregisterRequest) Reset() {
	*x = DeregisterRequest{}
	mi := &file_golem_golem_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeregisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeregisterRequest) ProtoMessage() {}

func (x *DeregisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_golem_golem_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeregisterRequest.ProtoReflect.Descriptor instead.
func (*DeregisterRequest) Descriptor() ([]byte, []int) {
	return file_golem_golem_proto_rawDescGZIP(), []int{12}
}

func (x *DeregisterRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *DeregisterRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type DeregisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	BaseResp      *BaseResp              `protobuf:"bytes,255,opt,name=base_resp,json=baseResp,proto3" json:"base_resp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeregisterResponse) Reset() {
	*x = DeregisterResponse{}
	mi := &file_golem_golem_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeregisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeregisterResponse) ProtoMessage() {}

func (x *DeregisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_golem_golem_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeregisterResponse.ProtoReflect.Descriptor instead.
func (*DeregisterResponse) Descriptor() ([]byte, []int) {
	return file_golem_golem_proto_rawDescGZIP(), []int{13}
}

func (x *DeregisterResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeregisterResponse) GetBaseResp() *BaseResp {
	if x != nil {
		return x.BaseResp
	}
	return nil
}

type ReportTaskResultRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	TaskResult    *TaskResult            `protobuf:"bytes,2,opt,name=task_result,json=taskResult,proto3" json:"task_result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportTaskResultRequest) Reset() {
	*x = ReportTaskResultRequest{}
	mi := &file_golem_golem_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportTaskResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportTaskResultRequest) ProtoMessage() {}

func (x *ReportTaskResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_golem_golem_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportTaskResultRequest.ProtoReflect.Descriptor instead.
func (*ReportTaskResultRequest) Descriptor() ([]byte, []int) {
	return file_golem_golem_proto_rawDescGZIP(), []int{14}
}

func (x *ReportTaskResultRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *ReportTaskResultRequest) GetTaskResult() *TaskResult {
	if x != nil {
		return x.TaskResult
	}
	return nil
}

type ReportTaskResultResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Acknowledged  bool                   `protobuf:"varint,1,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	BaseResp      *BaseResp              `protobuf:"bytes,255,opt,name=base_resp,json=baseResp,proto3" json:"base_resp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportTaskResultResponse) Reset() {
	*x = ReportTaskResultResponse{}
	mi := &file_golem_golem_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportTaskResultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportTaskResultResponse) ProtoMessage() {}

func (x *ReportTaskResultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_golem_golem_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportTaskResultResponse.ProtoReflect.Descriptor instead.
func (*ReportTaskResultResponse) Descriptor() ([]byte, []int) {
	return file_golem_golem_proto_rawDescGZIP(), []int{15}
}

func (x *ReportTaskResultResponse) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

func (x *ReportTaskResultResponse) GetBaseResp() *BaseResp {
	if x != nil {
		return x.BaseResp
	}
	return nil
}

type ReportTaskProgressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	TaskProgress  *TaskProgress          `protobuf:"bytes,2,opt,name=task_progress,json=taskProgress,proto3" json:"task_progress,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportTaskProgressRequest) Reset() {
	*x = ReportTaskProgressRequest{}
	mi := &file_golem_golem_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportTaskProgressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportTaskProgressRequest) ProtoMessage() {}

func (x *ReportTaskProgressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_golem_golem_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportTaskProgressRequest.ProtoReflect.Descriptor instead.
func (*ReportTaskProgressRequest) Descriptor() ([]byte, []int) {
	return file_golem_golem_proto_rawDescGZIP(), []int{16}
}

func (x *ReportTaskProgressRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *ReportTaskProgressRequest) GetTaskProgress() *TaskProgress {
	if x != nil {
		return x.TaskProgress
	}
	return nil
}

type ReportTaskProgressResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Acknowledged  bool                   `protobuf:"varint,1,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	BaseResp      *BaseResp              `protobuf:"bytes,255,opt,name=base_resp,json=baseResp,proto3" json:"base_resp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportTaskProgressResponse) Reset() {
	*x = ReportTaskProgressResponse{}
	mi := &file_golem_golem_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportTaskProgressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportTaskProgressResponse) ProtoMessage() {}

func (x *ReportTaskProgressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_golem_golem_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportTaskProgressResponse.ProtoReflect.Descriptor instead.
func (*ReportTaskProgressResponse) Descriptor() ([]byte, []int) {
	return file_golem_golem_proto_rawDescGZIP(), []int{17}
}

func (x *ReportTaskProgressResponse) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

func (x *ReportTaskProgressResponse) GetBaseResp() *BaseResp {
	if x != nil {
		return x.BaseResp
	}
	return nil
}

type DispatchTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *Task                  `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DispatchTaskRequest) Reset() {
	*x = DispatchTaskRequest{}
	mi := &file_golem_golem_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DispatchTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DispatchTaskRequest) ProtoMessage() {}

func (x *DispatchTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_golem_golem_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DispatchTaskRequest.ProtoReflect.Descriptor instead.
func (*DispatchTaskRequest) Descriptor() ([]byte, []int) {
	return file_golem_golem_proto_rawDescGZIP(), []int{18}
}

func (x *DispatchTaskRequest) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

type DispatchTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	RejectReason  string                 `protobuf:"bytes,2,opt,name=reject_reason,json=rejectReason,proto3" json:"reject_reason,omitempty"`
	BaseResp      *BaseResp              `protobuf:"bytes,255,opt,name=base_resp,json=baseResp,proto3" json:"base_resp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DispatchTaskResponse) Reset() {
	*x = DispatchTaskResponse{}
	mi := &file_golem_golem_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DispatchTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DispatchTaskResponse) ProtoMessage() {}

func (x *DispatchTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_golem_golem_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DispatchTaskResponse.ProtoReflect.Descriptor instead.
func (*DispatchTaskResponse) Descriptor() ([]byte, []int) {
	return file_golem_golem_proto_rawDescGZIP(), []int{19}
}

func (x *DispatchTaskResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *DispatchTaskResponse) GetRejectReason() string {
	if x != nil {
		return x.RejectReason
	}
	return ""
}

func (x *DispatchTaskResponse) GetBaseResp() *BaseResp {
	if x != nil {
		return x.BaseResp
	}
	return nil
}

type CancelTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelTaskRequest) Reset() {
	*x = CancelTaskRequest{}
	mi := &file_golem_golem_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelTaskRequest) ProtoMessage() {}

func (x *CancelTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_golem_golem_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelTaskRequest.ProtoReflect.Descriptor instead.
func (*CancelTaskRequest) Descriptor() ([]byte, []int) {
	return file_golem_golem_proto_rawDescGZIP(), []int{20}
}

func (x *CancelTaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *CancelTaskRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type CancelTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	BaseResp      *BaseResp              `protobuf:"bytes,255,opt,name=base_resp,json=baseResp,proto3" json:"base_resp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelTaskResponse) Reset() {
	*x = CancelTaskResponse{}
	mi := &file_golem_golem_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelTaskResponse) ProtoMessage() {}

func (x *CancelTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_golem_golem_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelTaskResponse.ProtoReflect.Descriptor instead.
func (*CancelTaskResponse) Descriptor() ([]byte, []int) {
	return file_golem_golem_proto_rawDescGZIP(), []int{21}
}

func (x *CancelTaskResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CancelTaskResponse) GetBaseResp() *BaseResp {
	if x != nil {
		return x.BaseResp
	}
	return nil
}

type DrainNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DrainNodeRequest) Reset() {
	*x = DrainNodeRequest{}
	mi := &file_golem_golem_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DrainNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DrainNodeRequest) ProtoMessage() {}

func (x *DrainNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_golem_golem_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DrainNodeRequest.ProtoReflect.Descriptor instead.
func (*DrainNodeRequest) Descriptor() ([]byte, []int) {
	return file_golem_golem_proto_rawDescGZIP(), []int{22}
}

func (x *DrainNodeRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type DrainNodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	BaseResp      *BaseResp              `protobuf:"bytes,255,opt,name=base_resp,json=baseResp,proto3" json:"base_resp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DrainNodeResponse) Reset() {
	*x = DrainNodeResponse{}
	mi := &file_golem_golem_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DrainNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DrainNodeResponse) ProtoMessage() {}

func (x *DrainNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_golem_golem_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DrainNodeResponse.ProtoReflect.Descriptor instead.
func (*DrainNodeResponse) Descriptor() ([]byte, []int) {
	return file_golem_golem_proto_rawDescGZIP(), []int{23}
}

func (x *DrainNodeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DrainNodeResponse) GetBaseResp() *BaseResp {
	if x != nil {
		return x.BaseResp
	}
	return nil
}

type ListNodesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusFilter  NodeStatus             `protobuf:"varint,1,opt,name=status_filter,json=statusFilter,proto3,enum=golem.NodeStatus" json:"status_filter,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNodesRequest) Reset() {
	*x = ListNodesRequest{}
	mi := &file_golem_golem_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNodesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNodesRequest) ProtoMessage() {}

func (x *ListNodesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_golem_golem_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNodesRequest.ProtoReflect.Descriptor instead.
func (*ListNodesRequest) Descriptor() ([]byte, []int) {
	return file_golem_golem_proto_rawDescGZIP(), []int{24}
}

func (x *ListNodesRequest) GetStatusFilter() NodeStatus {
	if x != nil {
		return x.StatusFilter
	}
	return NodeStatus_NODE_STATUS_UNSPECIFIED
}

func (x *ListNodesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListNodesRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListNodesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         []*NodeInfo            `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	TotalCount    int32                  `protobuf:"varint,3,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	BaseResp      *BaseResp              `protobuf:"bytes,255,opt,name=base_resp,json=baseResp,proto3" json:"base_resp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNodesResponse) Reset() {
	*x = ListNodesResponse{}
	mi := &file_golem_golem_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNodesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNodesResponse) ProtoMessage() {}

func (x *ListNodesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_golem_golem_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNodesResponse.ProtoReflect.Descriptor instead.
func (*ListNodesResponse) Descriptor() ([]byte, []int) {
	return file_golem_golem_proto_rawDescGZIP(), []int{25}
}

func (x *ListNodesResponse) GetNodes() []*NodeInfo {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *ListNodesResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

func (x *ListNodesResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ListNodesResponse) GetBaseResp() *BaseResp {
	if x != nil {
		return x.BaseResp
	}
	return nil
}

type GetNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNodeRequest) Reset() {
	*x = GetNodeRequest{}
	mi := &file_golem_golem_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodeRequest) ProtoMessage() {}

func (x *GetNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_golem_golem_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNodeRequest.ProtoReflect.Descriptor instead.
func (*GetNodeRequest) Descriptor() ([]byte, []int) {
	return file_golem_golem_proto_rawDescGZIP(), []int{26}
}

func (x *GetNodeRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type GetNodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeInfo      *NodeInfo              `protobuf:"bytes,1,opt,name=node_info,json=nodeInfo,proto3" json:"node_info,omitempty"`
	LoadInfo      *NodeLoadInfo          `protobuf:"bytes,2,opt,name=load_info,json=loadInfo,proto3" json:"load_info,omitempty"`
	BaseResp      *BaseResp              `protobuf:"bytes,255,opt,name=base_resp,json=baseResp,proto3" json:"base_resp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNodeResponse) Reset() {
	*x = GetNodeResponse{}
	mi := &file_golem_golem_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodeResponse) ProtoMessage() {}

func (x *GetNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_golem_golem_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNodeResponse.ProtoReflect.Descriptor instead.
func (*GetNodeResponse) Descriptor() ([]byte, []int) {
	return file_golem_golem_proto_rawDescGZIP(), []int{27}
}

func (x *GetNodeResponse) GetNodeInfo() *NodeInfo {
	if x != nil {
		return x.NodeInfo
	}
	return nil
}

func (x *GetNodeResponse) GetLoadInfo() *NodeLoadInfo {
	if x != nil {
		return x.LoadInfo
	}
	return nil
}

func (x *GetNodeResponse) GetBaseResp() *BaseResp {
	if x != nil {
		return x.BaseResp
	}
	return nil
}

type CordonNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CordonNodeRequest) Reset() {
	*x = CordonNodeRequest{}
	mi := &file_golem_golem_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CordonNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CordonNodeRequest) ProtoMessage() {}

func (x *CordonNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_golem_golem_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CordonNodeRequest.ProtoReflect.Descriptor instead.
func (*CordonNodeRequest) Descriptor() ([]byte, []int) {
	return file_golem_golem_proto_rawDescGZIP(), []int{28}
}

func (x *CordonNodeRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *CordonNodeRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type CordonNodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	BaseResp      *BaseResp              `protobuf:"bytes,255,opt,name=base_resp,json=baseResp,proto3" json:"base_resp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CordonNodeResponse) Reset() {
	*x = CordonNodeResponse{}
	mi := &file_golem_golem_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CordonNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CordonNodeResponse) ProtoMessage() {}

func (x *CordonNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_golem_golem_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CordonNodeResponse.ProtoReflect.Descriptor instead.
func (*CordonNodeResponse) Descriptor() ([]byte, []int) {
	return file_golem_golem_proto_rawDescGZIP(), []int{29}
}

func (x *CordonNodeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CordonNodeResponse) GetBaseResp() *BaseResp {
	if x != nil {
		return x.BaseResp
	}
	return nil
}

type UncordonNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UncordonNodeRequest) Reset() {
	*x = UncordonNodeRequest{}
	mi := &file_golem_golem_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UncordonNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UncordonNodeRequest) ProtoMessage() {}

func (x *UncordonNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_golem_golem_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UncordonNodeRequest.ProtoReflect.Descriptor instead.
func (*UncordonNodeRequest) Descriptor() ([]byte, []int) {
	return file_golem_golem_proto_rawDescGZIP(), []int{30}
}

func (x *UncordonNodeRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type UncordonNodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	BaseResp      *BaseResp              `protobuf:"bytes,255,opt,name=base_resp,json=baseResp,proto3" json:"base_resp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UncordonNodeResponse) Reset() {
	*x = UncordonNodeResponse{}
	mi := &file_golem_golem_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UncordonNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UncordonNodeResponse) ProtoMessage() {}

func (x *UncordonNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_golem_golem_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UncordonNodeResponse.ProtoReflect.Descriptor instead.
func (*UncordonNodeResponse) Descriptor() ([]byte, []int) {
	return file_golem_golem_proto_rawDescGZIP(), []int{31}
}

func (x *UncordonNodeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UncordonNodeResponse) GetBaseResp() *BaseResp {
	if x != nil {
		return x.BaseResp
	}
	return nil
}

var File_golem_golem_proto protoreflect.FileDescriptor

const file_golem_golem_proto_rawDesc = "" +
	"\n" +
	"\x11golem/golem.proto\x12\x05golem\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/duration.proto\"\\\n" +
	"\n" +
	"Capability\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"\xa8\x01\n" +
	"\n" +
	"SystemInfo\x12\x1b\n" +
	"\tcpu_cores\x18\x01 \x01(\x05R\bcpuCores\x12\x1b\n" +
	"\tmemory_mb\x18\x02 \x01(\x03R\bmemoryMb\x12 \n" +
	"\fdisk_free_mb\x18\x03 \x01(\x03R\n" +
	"diskFreeMb\x12\x0e\n" +
	"\x02os\x18\x04 \x01(\tR\x02os\x12\x12\n" +
	"\x04arch\x18\x05 \x01(\tR\x04arch\x12\x1a\n" +
	"\bhostname\x18\x06 \x01(\tR\bhostname\"\xe7\x03\n" +
	"\bNodeInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\x12)\n" +
	"\x06status\x18\x04 \x01(\x0e2\x11.golem.NodeStatusR\x06status\x122\n" +
	"\vsystem_info\x18\x05 \x01(\v2\x11.golem.SystemInfoR\n" +
	"systemInfo\x125\n" +
	"\fcapabilities\x18\x06 \x03(\v2\x11.golem.CapabilityR\fcapabilities\x123\n" +
	"\x06labels\x18\a \x03(\v2\x1b.golem.NodeInfo.LabelsEntryR\x06labels\x12\x18\n" +
	"\aversion\x18\b \x01(\tR\aversion\x12?\n" +
	"\rregistered_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\fregisteredAt\x12<\n" +
	"\flast_seen_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"lastSeenAt\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xbe\x01\n" +
	"\fNodeLoadInfo\x12\x1f\n" +
	"\vcpu_percent\x18\x01 \x01(\x01R\n" +
	"cpuPercent\x12%\n" +
	"\x0ememory_percent\x18\x02 \x01(\x01R\rmemoryPercent\x12 \n" +
	"\fdisk_free_mb\x18\x03 \x01(\x03R\n" +
	"diskFreeMb\x12!\n" +
	"\factive_tasks\x18\x04 \x01(\x05R\vactiveTasks\x12!\n" +
	"\fqueued_tasks\x18\x05 \x01(\x05R\vqueuedTasks\"\xaf\x05\n" +
	"\x04Task\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"skill_name\x18\x03 \x01(\tR\tskillName\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload\x12)\n" +
	"\x06status\x18\x05 \x01(\x0e2\x11.golem.TaskStatusR\x06status\x12/\n" +
	"\bpriority\x18\x06 \x01(\x0e2\x13.golem.TaskPriorityR\bpriority\x12(\n" +
	"\x10assigned_node_id\x18\a \x01(\tR\x0eassignedNodeId\x12\x1d\n" +
	"\n" +
	"session_id\x18\b \x01(\tR\tsessionId\x12\x19\n" +
	"\bagent_id\x18\t \x01(\tR\aagentId\x12\x16\n" +
	"\x06result\x18\n" +
	" \x01(\fR\x06result\x12\x14\n" +
	"\x05error\x18\v \x01(\tR\x05error\x123\n" +
	"\atimeout\x18\f \x01(\v2\x19.google.protobuf.DurationR\atimeout\x129\n" +
	"\n" +
	"created_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"started_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12=\n" +
	"\fcompleted_at\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt\x125\n" +
	"\bmetadata\x18\x10 \x03(\v2\x19.golem.Task.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa0\x01\n" +
	"\fTaskProgress\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12)\n" +
	"\x10progress_percent\x18\x02 \x01(\x01R\x0fprogressPercent\x12%\n" +
	"\x0estatus_message\x18\x03 \x01(\tR\rstatusMessage\x12%\n" +
	"\x0epartial_result\x18\x04 \x01(\fR\rpartialResult\"m\n" +
	"\n" +
	"TaskResult\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x16\n" +
	"\x06output\x18\x03 \x01(\fR\x06output\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"R\n" +
	"\bBaseResp\x12%\n" +
	"\x0estatus_message\x18\x01 \x01(\tR\rstatusMessage\x12\x1f\n" +
	"\vstatus_code\x18\x02 \x01(\x05R\n" +
	"statusCode\"\x90\x01\n" +
	"\x0fRegisterRequest\x12\x1d\n" +
	"\n" +
	"join_token\x18\x01 \x01(\tR\tjoinToken\x12,\n" +
	"\tnode_info\x18\x02 \x01(\v2\x0f.golem.NodeInfoR\bnodeInfo\x120\n" +
	"\tload_info\x18\x03 \x01(\v2\x13.golem.NodeLoadInfoR\bloadInfo\"\x9b\x01\n" +
	"\x10RegisterResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\x12#\n" +
	"\rreject_reason\x18\x03 \x01(\tR\frejectReason\x12-\n" +
	"\tbase_resp\x18\xff\x01 \x01(\v2\x0f.golem.BaseRespR\bbaseResp\"\x97\x01\n" +
	"\x10HeartbeatRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x120\n" +
	"\tload_info\x18\x02 \x01(\v2\x13.golem.NodeLoadInfoR\bloadInfo\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"g\n" +
	"\x11HeartbeatResponse\x12\"\n" +
	"\facknowledged\x18\x01 \x01(\bR\facknowledged\x12.\n" +
	"\x06action\x18\x02 \x01(\x0e2\x16.golem.HeartbeatActionR\x06action\"D\n" +
	"\x11DeregisterRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"]\n" +
	"\x12DeregisterResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12-\n" +
	"\tbase_resp\x18\xff\x01 \x01(\v2\x0f.golem.BaseRespR\bbaseResp\"f\n" +
	"\x17ReportTaskResultRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x122\n" +
	"\vtask_result\x18\x02 \x01(\v2\x11.golem.TaskResultR\n" +
	"taskResult\"m\n" +
	"\x18ReportTaskResultResponse\x12\"\n" +
	"\facknowledged\x18\x01 \x01(\bR\facknowledged\x12-\n" +
	"\tbase_resp\x18\xff\x01 \x01(\v2\x0f.golem.BaseRespR\bbaseResp\"n\n" +
	"\x19ReportTaskProgressRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x128\n" +
	"\rtask_progress\x18\x02 \x01(\v2\x13.golem.TaskProgressR\ftaskProgress\"o\n" +
	"\x1aReportTaskProgressResponse\x12\"\n" +
	"\facknowledged\x18\x01 \x01(\bR\facknowledged\x12-\n" +
	"\tbase_resp\x18\xff\x01 \x01(\v2\x0f.golem.BaseRespR\bbaseResp\"6\n" +
	"\x13DispatchTaskRequest\x12\x1f\n" +
	"\x04task\x18\x01 \x01(\v2\v.golem.TaskR\x04task\"\x86\x01\n" +
	"\x14DispatchTaskResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12#\n" +
	"\rreject_reason\x18\x02 \x01(\tR\frejectReason\x12-\n" +
	"\tbase_resp\x18\xff\x01 \x01(\v2\x0f.golem.BaseRespR\bbaseResp\"D\n" +
	"\x11CancelTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"]\n" +
	"\x12CancelTaskResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12-\n" +
	"\tbase_resp\x18\xff\x01 \x01(\v2\x0f.golem.BaseRespR\bbaseResp\"+\n" +
	"\x10DrainNodeRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\"\\\n" +
	"\x11DrainNodeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12-\n" +
	"\tbase_resp\x18\xff\x01 \x01(\v2\x0f.golem.BaseRespR\bbaseResp\"\x86\x01\n" +
	"\x10ListNodesRequest\x126\n" +
	"\rstatus_filter\x18\x01 \x01(\x0e2\x11.golem.NodeStatusR\fstatusFilter\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageToken\"\xb2\x01\n" +
	"\x11ListNodesResponse\x12%\n" +
	"\x05nodes\x18\x01 \x03(\v2\x0f.golem.NodeInfoR\x05nodes\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\x12\x1f\n" +
	"\vtotal_count\x18\x03 \x01(\x05R\n" +
	"totalCount\x12-\n" +
	"\tbase_resp\x18\xff\x01 \x01(\v2\x0f.golem.BaseRespR\bbaseResp\")\n" +
	"\x0eGetNodeRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\"\xa0\x01\n" +
	"\x0fGetNodeResponse\x12,\n" +
	"\tnode_info\x18\x01 \x01(\v2\x0f.golem.NodeInfoR\bnodeInfo\x120\n" +
	"\tload_info\x18\x02 \x01(\v2\x13.golem.NodeLoadInfoR\bloadInfo\x12-\n" +
	"\tbase_resp\x18\xff\x01 \x01(\v2\x0f.golem.BaseRespR\bbaseResp\"D\n" +
	"\x11CordonNodeRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"]\n" +
	"\x12CordonNodeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12-\n" +
	"\tbase_resp\x18\xff\x01 \x01(\v2\x0f.golem.BaseRespR\bbaseResp\".\n" +
	"\x13UncordonNodeRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\"_\n" +
	"\x14UncordonNodeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12-\n" +
	"\tbase_resp\x18\xff\x01 \x01(\v2\x0f.golem.BaseRespR\bbaseResp*\x8e\x01\n" +
	"\n" +
	"NodeStatus\x12\x1b\n" +
	"\x17NODE_STATUS_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12NODE_STATUS_ONLINE\x10\x01\x12\x17\n" +
	"\x13NODE_STATUS_OFFLINE\x10\x02\x12\x18\n" +
	"\x14NODE_STATUS_DRAINING\x10\x03\x12\x18\n" +
	"\x14NODE_STATUS_CORDONED\x10\x04*\xde\x01\n" +
	"\n" +
	"TaskStatus\x12\x1b\n" +
	"\x17TASK_STATUS_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13TASK_STATUS_PENDING\x10\x01\x12\x18\n" +
	"\x14TASK_STATUS_ASSIGNED\x10\x02\x12\x17\n" +
	"\x13TASK_STATUS_RUNNING\x10\x03\x12\x19\n" +
	"\x15TASK_STATUS_COMPLETED\x10\x04\x12\x16\n" +
	"\x12TASK_STATUS_FAILED\x10\x05\x12\x19\n" +
	"\x15TASK_STATUS_CANCELLED\x10\x06\x12\x19\n" +
	"\x15TASK_STATUS_TIMED_OUT\x10\a*\x92\x01\n" +
	"\fTaskPriority\x12\x1d\n" +
	"\x19TASK_PRIORITY_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11TASK_PRIORITY_LOW\x10\x01\x12\x18\n" +
	"\x14TASK_PRIORITY_NORMAL\x10\x05\x12\x16\n" +
	"\x12TASK_PRIORITY_HIGH\x10\b\x12\x1a\n" +
	"\x16TASK_PRIORITY_CRITICAL\x10\n" +
	"*\x89\x01\n" +
	"\x0fHeartbeatAction\x12 \n" +
	"\x1cHEARTBEAT_ACTION_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15HEARTBEAT_ACTION_NONE\x10\x01\x12\x1a\n" +
	"\x16HEARTBEAT_ACTION_DRAIN\x10\x02\x12\x1d\n" +
	"\x19HEARTBEAT_ACTION_SHUTDOWN\x10\x032\x86\x03\n" +
	"\x10GolemNodeService\x12;\n" +
	"\bRegister\x12\x16.golem.RegisterRequest\x1a\x17.golem.RegisterResponse\x12B\n" +
	"\tHeartbeat\x12\x17.golem.HeartbeatRequest\x1a\x18.golem.HeartbeatResponse(\x010\x01\x12A\n" +
	"\n" +
	"Deregister\x12\x18.golem.DeregisterRequest\x1a\x19.golem.DeregisterResponse\x12S\n" +
	"\x10ReportTaskResult\x12\x1e.golem.ReportTaskResultRequest\x1a\x1f.golem.ReportTaskResultResponse\x12Y\n" +
	"\x12ReportTaskProgress\x12 .golem.ReportTaskProgressRequest\x1a!.golem.ReportTaskProgressResponse2\xe4\x01\n" +
	"\x16HivemindControlService\x12G\n" +
	"\fDispatchTask\x12\x1a.golem.DispatchTaskRequest\x1a\x1b.golem.DispatchTaskResponse\x12A\n" +
	"\n" +
	"CancelTask\x12\x18.golem.CancelTaskRequest\x1a\x19.golem.CancelTaskResponse\x12>\n" +
	"\tDrainNode\x12\x17.golem.DrainNodeRequest\x1a\x18.golem.DrainNodeResponse2\x9c\x02\n" +
	"\x14HivemindAdminService\x12>\n" +
	"\tListNodes\x12\x17.golem.ListNodesRequest\x1a\x18.golem.ListNodesResponse\x128\n" +
	"\aGetNode\x12\x15.golem.GetNodeRequest\x1a\x16.golem.GetNodeResponse\x12A\n" +
	"\n" +
	"CordonNode\x12\x18.golem.CordonNodeRequest\x1a\x19.golem.CordonNodeResponse\x12G\n" +
	"\fUncordonNode\x12\x1a.golem.UncordonNodeRequest\x1a\x1b.golem.UncordonNodeResponseB-Z+github.com/kiosk404/echoryn/pkg/proto/golemb\x06proto3"

var (
	file_golem_golem_proto_rawDescOnce sync.Once
	file_golem_golem_proto_rawDescData []byte
)

func file_golem_golem_proto_rawDescGZIP() []byte {
	file_golem_golem_proto_rawDescOnce.Do(func() {
		file_golem_golem_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_golem_golem_proto_rawDesc), len(file_golem_golem_proto_rawDesc)))
	})
	return file_golem_golem_proto_rawDescData
}

var file_golem_golem_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_golem_golem_proto_msgTypes = make([]protoimpl.MessageInfo, 34)
var file_golem_golem_proto_goTypes = []any{
	(NodeStatus)(0),                    // 0: golem.NodeStatus
	(TaskStatus)(0),                    // 1: golem.TaskStatus
	(TaskPriority)(0),                  // 2: golem.TaskPriority
	(HeartbeatAction)(0),               // 3: golem.HeartbeatAction
	(*Capability)(nil),                 // 4: golem.Capability
	(*SystemInfo)(nil),                 // 5: golem.SystemInfo
	(*NodeInfo)(nil),                   // 6: golem.NodeInfo
	(*NodeLoadInfo)(nil),               // 7: golem.NodeLoadInfo
	(*Task)(nil),                       // 8: golem.Task
	(*TaskProgress)(nil),               // 9: golem.TaskProgress
	(*TaskResult)(nil),                 // 10: golem.TaskResult
	(*BaseResp)(nil),                   // 11: golem.BaseResp
	(*RegisterRequest)(nil),            // 12: golem.RegisterRequest
	(*RegisterResponse)(nil),           // 13: golem.RegisterResponse
	(*HeartbeatRequest)(nil),           // 14: golem.HeartbeatRequest
	(*HeartbeatResponse)(nil),          // 15: golem.HeartbeatResponse
	(*DeregisterRequest)(nil),          // 16: golem.DeregisterRequest
	(*DeregisterResponse)(nil),         // 17: golem.DeregisterResponse
	(*ReportTaskResultRequest)(nil),    // 18: golem.ReportTaskResultRequest
	(*ReportTaskResultResponse)(nil),   // 19: golem.ReportTaskResultResponse
	(*ReportTaskProgressRequest)(nil),  // 20: golem.ReportTaskProgressRequest
	(*ReportTaskProgressResponse)(nil), // 21: golem.ReportTaskProgressResponse
	(*DispatchTaskRequest)(nil),        // 22: golem.DispatchTaskRequest
	(*DispatchTaskResponse)(nil),       // 23: golem.DispatchTaskResponse
	(*CancelTaskRequest)(nil),          // 24: golem.CancelTaskRequest
	(*CancelTaskResponse)(nil),         // 25: golem.CancelTaskResponse
	(*DrainNodeRequest)(nil),           // 26: golem.DrainNodeRequest
	(*DrainNodeResponse)(nil),          // 27: golem.DrainNodeResponse
	(*ListNodesRequest)(nil),           // 28: golem.ListNodesRequest
	(*ListNodesResponse)(nil),          // 29: golem.ListNodesResponse
	(*GetNodeRequest)(nil),             // 30: golem.GetNodeRequest
	(*GetNodeResponse)(nil),            // 31: golem.GetNodeResponse
	(*CordonNodeRequest)(nil),          // 32: golem.CordonNodeRequest
	(*CordonNodeResponse)(nil),         // 33: golem.CordonNodeResponse
	(*UncordonNodeRequest)(nil),        // 34: golem.UncordonNodeRequest
	(*UncordonNodeResponse)(nil),       // 35: golem.UncordonNodeResponse
	nil,                                // 36: golem.NodeInfo.LabelsEntry
	nil,                                // 37: golem.Task.MetadataEntry
	(*timestamppb.Timestamp)(nil),      // 38: google.protobuf.Timestamp
	(*durationpb.Duration)(nil),        // 39: google.protobuf.Duration
}
var file_golem_golem_proto_depIdxs = []int32{
	0,  // 0: golem.NodeInfo.status:type_name -> golem.NodeStatus
	5,  // 1: golem.NodeInfo.system_info:type_name -> golem.SystemInfo
	4,  // 2: golem.NodeInfo.capabilities:type_name -> golem.Capability
	36, // 3: golem.NodeInfo.labels:type_name -> golem.NodeInfo.LabelsEntry
	38, // 4: golem.NodeInfo.registered_at:type_name -> google.protobuf.Timestamp
	38, // 5: golem.NodeInfo.last_seen_at:type_name -> google.protobuf.Timestamp
	1,  // 6: golem.Task.status:type_name -> golem.TaskStatus
	2,  // 7: golem.Task.priority:type_name -> golem.TaskPriority
	39, // 8: golem.Task.timeout:type_name -> google.protobuf.Duration
	38, // 9: golem.Task.created_at:type_name -> google.protobuf.Timestamp
	38, // 10: golem.Task.started_at:type_name -> google.protobuf.Timestamp
	38, // 11: golem.Task.completed_at:type_name -> google.protobuf.Timestamp
	37, // 12: golem.Task.metadata:type_name -> golem.Task.MetadataEntry
	6,  // 13: golem.RegisterRequest.node_info:type_name -> golem.NodeInfo
	7,  // 14: golem.RegisterRequest.load_info:type_name -> golem.NodeLoadInfo
	11, // 15: golem.RegisterResponse.base_resp:type_name -> golem.BaseResp
	7,  // 16: golem.HeartbeatRequest.load_info:type_name -> golem.NodeLoadInfo
	38, // 17: golem.HeartbeatRequest.timestamp:type_name -> google.protobuf.Timestamp
	3,  // 18: golem.HeartbeatResponse.action:type_name -> golem.HeartbeatAction
	11, // 19: golem.DeregisterResponse.base_resp:type_name -> golem.BaseResp
	10, // 20: golem.ReportTaskResultRequest.task_result:type_name -> golem.TaskResult
	11, // 21: golem.ReportTaskResultResponse.base_resp:type_name -> golem.BaseResp
	9,  // 22: golem.ReportTaskProgressRequest.task_progress:type_name -> golem.TaskProgress
	11, // 23: golem.ReportTaskProgressResponse.base_resp:type_name -> golem.BaseResp
	8,  // 24: golem.DispatchTaskRequest.task:type_name -> golem.Task
	11, // 25: golem.DispatchTaskResponse.base_resp:type_name -> golem.BaseResp
	11, // 26: golem.CancelTaskResponse.base_resp:type_name -> golem.BaseResp
	11, // 27: golem.DrainNodeResponse.base_resp:type_name -> golem.BaseResp
	0,  // 28: golem.ListNodesRequest.status_filter:type_name -> golem.NodeStatus
	6,  // 29: golem.ListNodesResponse.nodes:type_name -> golem.NodeInfo
	11, // 30: golem.ListNodesResponse.base_resp:type_name -> golem.BaseResp
	6,  // 31: golem.GetNodeResponse.node_info:type_name -> golem.NodeInfo
	7,  // 32: golem.GetNodeResponse.load_info:type_name -> golem.NodeLoadInfo
	11, // 33: golem.GetNodeResponse.base_resp:type_name -> golem.BaseResp
	11, // 34: golem.CordonNodeResponse.base_resp:type_name -> golem.BaseResp
	11, // 35: golem.UncordonNodeResponse.base_resp:type_name -> golem.BaseResp
	12, // 36: golem.GolemNodeService.Register:input_type -> golem.RegisterRequest
	14, // 37: golem.GolemNodeService.Heartbeat:input_type -> golem.HeartbeatRequest
	16, // 38: golem.GolemNodeService.Deregister:input_type -> golem.DeregisterRequest
	18, // 39: golem.GolemNodeService.ReportTaskResult:input_type -> golem.ReportTaskResultRequest
	20, // 40: golem.GolemNodeService.ReportTaskProgress:input_type -> golem.ReportTaskProgressRequest
	22, // 41: golem.HivemindControlService.DispatchTask:input_type -> golem.DispatchTaskRequest
	24, // 42: golem.HivemindControlService.CancelTask:input_type -> golem.CancelTaskRequest
	26, // 43: golem.HivemindControlService.DrainNode:input_type -> golem.DrainNodeRequest
	28, // 44: golem.HivemindAdminService.ListNodes:input_type -> golem.ListNodesRequest
	30, // 45: golem.HivemindAdminService.GetNode:input_type -> golem.GetNodeRequest
	32, // 46: golem.HivemindAdminService.CordonNode:input_type -> golem.CordonNodeRequest
	34, // 47: golem.HivemindAdminService.UncordonNode:input_type -> golem.UncordonNodeRequest
	13, // 48: golem.GolemNodeService.Register:output_type -> golem.RegisterResponse
	15, // 49: golem.GolemNodeService.Heartbeat:output_type -> golem.HeartbeatResponse
	17, // 50: golem.GolemNodeService.Deregister:output_type -> golem.DeregisterResponse
	19, // 51: golem.GolemNodeService.ReportTaskResult:output_type -> golem.ReportTaskResultResponse
	21, // 52: golem.GolemNodeService.ReportTaskProgress:output_type -> golem.ReportTaskProgressResponse
	23, // 53: golem.HivemindControlService.DispatchTask:output_type -> golem.DispatchTaskResponse
	25, // 54: golem.HivemindControlService.CancelTask:output_type -> golem.CancelTaskResponse
	27, // 55: golem.HivemindControlService.DrainNode:output_type -> golem.DrainNodeResponse
	29, // 56: golem.HivemindAdminService.ListNodes:output_type -> golem.ListNodesResponse
	31, // 57: golem.HivemindAdminService.GetNode:output_type -> golem.GetNodeResponse
	33, // 58: golem.HivemindAdminService.CordonNode:output_type -> golem.CordonNodeResponse
	35, // 59: golem.HivemindAdminService.UncordonNode:output_type -> golem.UncordonNodeResponse
	48, // [48:60] is the sub-list for method output_type
	36, // [36:48] is the sub-list for method input_type
	36, // [36:36] is the sub-list for extension type_name
	36, // [36:36] is the sub-list for extension extendee
	0,  // [0:36] is the sub-list for field type_name
}

func init() { file_golem_golem_proto_init() }
func file_golem_golem_proto_init() {
	if File_golem_golem_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_golem_golem_proto_rawDesc), len(file_golem_golem_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   34,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_golem_golem_proto_goTypes,
		DependencyIndexes: file_golem_golem_proto_depIdxs,
		EnumInfos:         file_golem_golem_proto_enumTypes,
		MessageInfos:      file_golem_golem_proto_msgTypes,
	}.Build()
	File_golem_golem_proto = out.File
	file_golem_golem_proto_goTypes = nil
	file_golem_golem_proto_depIdxs = nil
}
