// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: base/base.proto

package base

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TrafficEnv 流量环境配置
type TrafficEnv struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Open          bool                   `protobuf:"varint,1,opt,name=open,proto3" json:"open,omitempty"`
	Env           string                 `protobuf:"bytes,2,opt,name=env,proto3" json:"env,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrafficEnv) Reset() {
	*x = TrafficEnv{}
	mi := &file_base_base_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrafficEnv) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrafficEnv) ProtoMessage() {}

func (x *TrafficEnv) ProtoReflect() protoreflect.Message {
	mi := &file_base_base_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrafficEnv.ProtoReflect.Descriptor instead.
func (*TrafficEnv) Descriptor() ([]byte, []int) {
	return file_base_base_proto_rawDescGZIP(), []int{0}
}

func (x *TrafficEnv) GetOpen() bool {
	if x != nil {
		return x.Open
	}
	return false
}

func (x *TrafficEnv) GetEnv() string {
	if x != nil {
		return x.Env
	}
	return ""
}

// Base 基础请求信息
type Base struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LogId         string                 `protobuf:"bytes,1,opt,name=log_id,json=logId,proto3" json:"log_id,omitempty"`
	Caller        string                 `protobuf:"bytes,2,opt,name=caller,proto3" json:"caller,omitempty"`
	Addr          string                 `protobuf:"bytes,3,opt,name=addr,proto3" json:"addr,omitempty"`
	Client        string                 `protobuf:"bytes,4,opt,name=client,proto3" json:"client,omitempty"`
	TrafficEnv    *TrafficEnv            `protobuf:"bytes,5,opt,name=traffic_env,json=trafficEnv,proto3" json:"traffic_env,omitempty"`
	Extra         map[string]string      `protobuf:"bytes,6,rep,name=extra,proto3" json:"extra,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Base) Reset() {
	*x = Base{}
	mi := &file_base_base_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Base) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Base) ProtoMessage() {}

func (x *Base) ProtoReflect() protoreflect.Message {
	mi := &file_base_base_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Base.ProtoReflect.Descriptor instead.
func (*Base) Descriptor() ([]byte, []int) {
	return file_base_base_proto_rawDescGZIP(), []int{1}
}

func (x *Base) GetLogId() string {
	if x != nil {
		return x.LogId
	}
	return ""
}

func (x *Base) GetCaller() string {
	if x != nil {
		return x.Caller
	}
	return ""
}

func (x *Base) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *Base) GetClient() string {
	if x != nil {
		return x.Client
	}
	return ""
}

func (x *Base) GetTrafficEnv() *TrafficEnv {
	if x != nil {
		return x.TrafficEnv
	}
	return nil
}

func (x *Base) GetExtra() map[string]string {
	if x != nil {
		return x.Extra
	}
	return nil
}

// BaseResp 基础响应信息
type BaseResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusMessage string                 `protobuf:"bytes,1,opt,name=status_message,json=statusMessage,proto3" json:"status_message,omitempty"`
	StatusCode    int32                  `protobuf:"varint,2,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Extra         map[string]string      `protobuf:"bytes,3,rep,name=extra,proto3" json:"extra,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaseResp) Reset() {
	*x = BaseResp{}
	mi := &file_base_base_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseResp) ProtoMessage() {}

func (x *BaseResp) ProtoReflect() protoreflect.Message {
	mi := &file_base_base_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseResp.ProtoReflect.Descriptor instead.
func (*BaseResp) Descriptor() ([]byte, []int) {
	return file_base_base_proto_rawDescGZIP(), []int{2}
}

func (x *BaseResp) GetStatusMessage() string {
	if x != nil {
		return x.StatusMessage
	}
	return ""
}

func (x *BaseResp) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *BaseResp) GetExtra() map[string]string {
	if x != nil {
		return x.Extra
	}
	return nil
}

// EmptyReq 空请求
type EmptyReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyReq) Reset() {
	*x = EmptyReq{}
	mi := &file_base_base_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyReq) ProtoMessage() {}

func (x *EmptyReq) ProtoReflect() protoreflect.Message {
	mi := &file_base_base_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyReq.ProtoReflect.Descriptor instead.
func (*EmptyReq) Descriptor() ([]byte, []int) {
	return file_base_base_proto_rawDescGZIP(), []int{3}
}

// EmptyData 空数据
type EmptyData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyData) Reset() {
	*x = EmptyData{}
	mi := &file_base_base_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyData) ProtoMessage() {}

func (x *EmptyData) ProtoReflect() protoreflect.Message {
	mi := &file_base_base_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyData.ProtoReflect.Descriptor instead.
func (*EmptyData) Descriptor() ([]byte, []int) {
	return file_base_base_proto_rawDescGZIP(), []int{4}
}

// EmptyResp 空响应
type EmptyResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data          *EmptyData             `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyResp) Reset() {
	*x = EmptyResp{}
	mi := &file_base_base_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyResp) ProtoMessage() {}

func (x *EmptyResp) ProtoReflect() protoreflect.Message {
	mi := &file_base_base_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyResp.ProtoReflect.Descriptor instead.
func (*EmptyResp) Descriptor() ([]byte, []int) {
	return file_base_base_proto_rawDescGZIP(), []int{5}
}

func (x *EmptyResp) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *EmptyResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *EmptyResp) GetData() *EmptyData {
	if x != nil {
		return x.Data
	}
	return nil
}

// EmptyRpcReq RPC 空请求
type EmptyRpcReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *Base                  `protobuf:"bytes,255,opt,name=base,proto3" json:"base,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyRpcReq) Reset() {
	*x = EmptyRpcReq{}
	mi := &file_base_base_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyRpcReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyRpcReq) ProtoMessage() {}

func (x *EmptyRpcReq) ProtoReflect() protoreflect.Message {
	mi := &file_base_base_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyRpcReq.ProtoReflect.Descriptor instead.
func (*EmptyRpcReq) Descriptor() ([]byte, []int) {
	return file_base_base_proto_rawDescGZIP(), []int{6}
}

func (x *EmptyRpcReq) GetBase() *Base {
	if x != nil {
		return x.Base
	}
	return nil
}

// EmptyRpcResp RPC 空响应
type EmptyRpcResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BaseResp      *BaseResp              `protobuf:"bytes,255,opt,name=base_resp,json=baseResp,proto3" json:"base_resp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyRpcResp) Reset() {
	*x = EmptyRpcResp{}
	mi := &file_base_base_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyRpcResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyRpcResp) ProtoMessage() {}

func (x *EmptyRpcResp) ProtoReflect() protoreflect.Message {
	mi := &file_base_base_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyRpcResp.ProtoReflect.Descriptor instead.
func (*EmptyRpcResp) Descriptor() ([]byte, []int) {
	return file_base_base_proto_rawDescGZIP(), []int{7}
}

func (x *EmptyRpcResp) GetBaseResp() *BaseResp {
	if x != nil {
		return x.BaseResp
	}
	return nil
}

var File_base_base_proto protoreflect.FileDescriptor

const file_base_base_proto_rawDesc = "" +
	"\n" +
	"\x0fbase/base.proto\x12\x04base\"2\n" +
	"\n" +
	"TrafficEnv\x12\x12\n" +
	"\x04open\x18\x01 \x01(\bR\x04open\x12\x10\n" +
	"\x03env\x18\x02 \x01(\tR\x03env\"\xfb\x01\n" +
	"\x04Base\x12\x15\n" +
	"\x06log_id\x18\x01 \x01(\tR\x05logId\x12\x16\n" +
	"\x06caller\x18\x02 \x01(\tR\x06caller\x12\x12\n" +
	"\x04addr\x18\x03 \x01(\tR\x04addr\x12\x16\n" +
	"\x06client\x18\x04 \x01(\tR\x06client\x121\n" +
	"\vtraffic_env\x18\x05 \x01(\v2\x10.base.TrafficEnvR\n" +
	"trafficEnv\x12+\n" +
	"\x05extra\x18\x06 \x03(\v2\x15.base.Base.ExtraEntryR\x05extra\x1a8\n" +
	"\n" +
	"ExtraEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xbd\x01\n" +
	"\bBaseResp\x12%\n" +
	"\x0estatus_message\x18\x01 \x01(\tR\rstatusMessage\x12\x1f\n" +
	"\vstatus_code\x18\x02 \x01(\x05R\n" +
	"statusCode\x12/\n" +
	"\x05extra\x18\x03 \x03(\v2\x19.base.BaseResp.ExtraEntryR\x05extra\x1a8\n" +
	"\n" +
	"ExtraEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\n" +
	"\n" +
	"\bEmptyReq\"\v\n" +
	"\tEmptyData\"V\n" +
	"\tEmptyResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12#\n" +
	"\x04data\x18\x03 \x01(\v2\x0f.base.EmptyDataR\x04data\".\n" +
	"\vEmptyRpcReq\x12\x1f\n" +
	"\x04base\x18\xff\x01 \x01(\v2\n" +
	".base.BaseR\x04base\"<\n" +
	"\fEmptyRpcResp\x12,\n" +
	"\tbase_resp\x18\xff\x01 \x01(\v2\x0e.base.BaseRespR\bbaseRespB,Z*github.com/kiosk404/echoryn/pkg/proto/baseb\x06proto3"

var (
	file_base_base_proto_rawDescOnce sync.Once
	file_base_base_proto_rawDescData []byte
)

func file_base_base_proto_rawDescGZIP() []byte {
	file_base_base_proto_rawDescOnce.Do(func() {
		file_base_base_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_base_base_proto_rawDesc), len(file_base_base_proto_rawDesc)))
	})
	return file_base_base_proto_rawDescData
}

var file_base_base_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_base_base_proto_goTypes = []any{
	(*TrafficEnv)(nil),   // 0: base.TrafficEnv
	(*Base)(nil),         // 1: base.Base
	(*BaseResp)(nil),     // 2: base.BaseResp
	(*EmptyReq)(nil),     // 3: base.EmptyReq
	(*EmptyData)(nil),    // 4: base.EmptyData
	(*EmptyResp)(nil),    // 5: base.EmptyResp
	(*EmptyRpcReq)(nil),  // 6: base.EmptyRpcReq
	(*EmptyRpcResp)(nil), // 7: base.EmptyRpcResp
	nil,                  // 8: base.Base.ExtraEntry
	nil,                  // 9: base.BaseResp.ExtraEntry
}
var file_base_base_proto_depIdxs = []int32{
	0, // 0: base.Base.traffic_env:type_name -> base.TrafficEnv
	8, // 1: base.Base.extra:type_name -> base.Base.ExtraEntry
	9, // 2: base.BaseResp.extra:type_name -> base.BaseResp.ExtraEntry
	4, // 3: base.EmptyResp.data:type_name -> base.EmptyData
	1, // 4: base.EmptyRpcReq.base:type_name -> base.Base
	2, // 5: base.EmptyRpcResp.base_resp:type_name -> base.BaseResp
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_base_base_proto_init() }
func file_base_base_proto_init() {
	if File_base_base_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_base_base_proto_rawDesc), len(file_base_base_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_base_base_proto_goTypes,
		DependencyIndexes: file_base_base_proto_depIdxs,
		MessageInfos:      file_base_base_proto_msgTypes,
	}.Build()
	File_base_base_proto = out.File
	file_base_base_proto_goTypes = nil
	file_base_base_proto_depIdxs = nil
}
