// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: api/api.proto

package api

import (
	base "github.com/kiosk404/echoryn/pkg/proto/base"
	golem "github.com/kiosk404/echoryn/pkg/proto/golem"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// HeartbeatAction 心跳响应中 Hivemind 可下发的控制指令
type HeartbeatAction int32

const (
	HeartbeatAction_HEARTBEAT_ACTION_UNSPECIFIED HeartbeatAction = 0
	HeartbeatAction_HEARTBEAT_ACTION_NONE        HeartbeatAction = 1 // 无操作
	HeartbeatAction_HEARTBEAT_ACTION_DRAIN       HeartbeatAction = 2 // 开始排水
	HeartbeatAction_HEARTBEAT_ACTION_SHUTDOWN    HeartbeatAction = 3 // 要求关闭
)

// Enum value maps for HeartbeatAction.
var (
	HeartbeatAction_name = map[int32]string{
		0: "HEARTBEAT_ACTION_UNSPECIFIED",
		1: "HEARTBEAT_ACTION_NONE",
		2: "HEARTBEAT_ACTION_DRAIN",
		3: "HEARTBEAT_ACTION_SHUTDOWN",
	}
	HeartbeatAction_value = map[string]int32{
		"HEARTBEAT_ACTION_UNSPECIFIED": 0,
		"HEARTBEAT_ACTION_NONE":        1,
		"HEARTBEAT_ACTION_DRAIN":       2,
		"HEARTBEAT_ACTION_SHUTDOWN":    3,
	}
)

func (x HeartbeatAction) Enum() *HeartbeatAction {
	p := new(HeartbeatAction)
	*p = x
	return p
}

func (x HeartbeatAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HeartbeatAction) Descriptor() protoreflect.EnumDescriptor {
	return file_api_api_proto_enumTypes[0].Descriptor()
}

func (HeartbeatAction) Type() protoreflect.EnumType {
	return &file_api_api_proto_enumTypes[0]
}

func (x HeartbeatAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HeartbeatAction.Descriptor instead.
func (HeartbeatAction) EnumDescriptor() ([]byte, []int) {
	return file_api_api_proto_rawDescGZIP(), []int{0}
}

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JoinToken     string                 `protobuf:"bytes,1,opt,name=join_token,json=joinToken,proto3" json:"join_token,omitempty"` // 加入令牌 (由 echoadm 生成)
	NodeInfo      *golem.NodeInfo        `protobuf:"bytes,2,opt,name=node_info,json=nodeInfo,proto3" json:"node_info,omitempty"`    // 节点信息
	LoadInfo      *golem.NodeLoadInfo    `protobuf:"bytes,3,opt,name=load_info,json=loadInfo,proto3" json:"load_info,omitempty"`    // 初始负载信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_api_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_api_api_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetJoinToken() string {
	if x != nil {
		return x.JoinToken
	}
	return ""
}

func (x *RegisterRequest) GetNodeInfo() *golem.NodeInfo {
	if x != nil {
		return x.NodeInfo
	}
	return nil
}

func (x *RegisterRequest) GetLoadInfo() *golem.NodeLoadInfo {
	if x != nil {
		return x.LoadInfo
	}
	return nil
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`                            // 是否接受注册
	NodeId        string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`                   // Hivemind 分配/确认的节点 ID
	RejectReason  string                 `protobuf:"bytes,3,opt,name=reject_reason,json=rejectReason,proto3" json:"reject_reason,omitempty"` // 拒绝原因 (如果不接受)
	BaseResp      *base.BaseResp         `protobuf:"bytes,255,opt,name=base_resp,json=baseResp,proto3" json:"base_resp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_api_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_api_api_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *RegisterResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *RegisterResponse) GetRejectReason() string {
	if x != nil {
		return x.RejectReason
	}
	return ""
}

func (x *RegisterResponse) GetBaseResp() *base.BaseResp {
	if x != nil {
		return x.BaseResp
	}
	return nil
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`       // 节点 ID
	LoadInfo      *golem.NodeLoadInfo    `protobuf:"bytes,2,opt,name=load_info,json=loadInfo,proto3" json:"load_info,omitempty"` // 当前负载
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`               // 心跳时间戳
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_api_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_api_api_proto_rawDescGZIP(), []int{2}
}

func (x *HeartbeatRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *HeartbeatRequest) GetLoadInfo() *golem.NodeLoadInfo {
	if x != nil {
		return x.LoadInfo
	}
	return nil
}

func (x *HeartbeatRequest) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Acknowledged  bool                   `protobuf:"varint,1,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`              // 心跳确认
	Action        HeartbeatAction        `protobuf:"varint,2,opt,name=action,proto3,enum=api.HeartbeatAction" json:"action,omitempty"` // 控制指令
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_api_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_api_api_proto_rawDescGZIP(), []int{3}
}

func (x *HeartbeatResponse) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

func (x *HeartbeatResponse) GetAction() HeartbeatAction {
	if x != nil {
		return x.Action
	}
	return HeartbeatAction_HEARTBEAT_ACTION_UNSPECIFIED
}

type DeregisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"` // 注销原因 (e.g. "graceful_shutdown", "maintenance")
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeregisterRequest) Reset() {
	*x = DeregisterRequest{}
	mi := &file_api_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeregisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeregisterRequest) ProtoMessage() {}

func (x *DeregisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeregisterRequest.ProtoReflect.Descriptor instead.
func (*DeregisterRequest) Descriptor() ([]byte, []int) {
	return file_api_api_proto_rawDescGZIP(), []int{4}
}

func (x *DeregisterRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *DeregisterRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type DeregisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	BaseResp      *base.BaseResp         `protobuf:"bytes,255,opt,name=base_resp,json=baseResp,proto3" json:"base_resp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeregisterResponse) Reset() {
	*x = DeregisterResponse{}
	mi := &file_api_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeregisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeregisterResponse) ProtoMessage() {}

func (x *DeregisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeregisterResponse.ProtoReflect.Descriptor instead.
func (*DeregisterResponse) Descriptor() ([]byte, []int) {
	return file_api_api_proto_rawDescGZIP(), []int{5}
}

func (x *DeregisterResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeregisterResponse) GetBaseResp() *base.BaseResp {
	if x != nil {
		return x.BaseResp
	}
	return nil
}

type ReportTaskResultRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	TaskResult    *golem.TaskResult      `protobuf:"bytes,2,opt,name=task_result,json=taskResult,proto3" json:"task_result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportTaskResultRequest) Reset() {
	*x = ReportTaskResultRequest{}
	mi := &file_api_api_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportTaskResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportTaskResultRequest) ProtoMessage() {}

func (x *ReportTaskResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportTaskResultRequest.ProtoReflect.Descriptor instead.
func (*ReportTaskResultRequest) Descriptor() ([]byte, []int) {
	return file_api_api_proto_rawDescGZIP(), []int{6}
}

func (x *ReportTaskResultRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *ReportTaskResultRequest) GetTaskResult() *golem.TaskResult {
	if x != nil {
		return x.TaskResult
	}
	return nil
}

type ReportTaskResultResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Acknowledged  bool                   `protobuf:"varint,1,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	BaseResp      *base.BaseResp         `protobuf:"bytes,255,opt,name=base_resp,json=baseResp,proto3" json:"base_resp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportTaskResultResponse) Reset() {
	*x = ReportTaskResultResponse{}
	mi := &file_api_api_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportTaskResultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportTaskResultResponse) ProtoMessage() {}

func (x *ReportTaskResultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportTaskResultResponse.ProtoReflect.Descriptor instead.
func (*ReportTaskResultResponse) Descriptor() ([]byte, []int) {
	return file_api_api_proto_rawDescGZIP(), []int{7}
}

func (x *ReportTaskResultResponse) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

func (x *ReportTaskResultResponse) GetBaseResp() *base.BaseResp {
	if x != nil {
		return x.BaseResp
	}
	return nil
}

type ReportTaskProgressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	TaskProgress  *golem.TaskProgress    `protobuf:"bytes,2,opt,name=task_progress,json=taskProgress,proto3" json:"task_progress,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportTaskProgressRequest) Reset() {
	*x = ReportTaskProgressRequest{}
	mi := &file_api_api_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportTaskProgressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportTaskProgressRequest) ProtoMessage() {}

func (x *ReportTaskProgressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportTaskProgressRequest.ProtoReflect.Descriptor instead.
func (*ReportTaskProgressRequest) Descriptor() ([]byte, []int) {
	return file_api_api_proto_rawDescGZIP(), []int{8}
}

func (x *ReportTaskProgressRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *ReportTaskProgressRequest) GetTaskProgress() *golem.TaskProgress {
	if x != nil {
		return x.TaskProgress
	}
	return nil
}

type ReportTaskProgressResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Acknowledged  bool                   `protobuf:"varint,1,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	BaseResp      *base.BaseResp         `protobuf:"bytes,255,opt,name=base_resp,json=baseResp,proto3" json:"base_resp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportTaskProgressResponse) Reset() {
	*x = ReportTaskProgressResponse{}
	mi := &file_api_api_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportTaskProgressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportTaskProgressResponse) ProtoMessage() {}

func (x *ReportTaskProgressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportTaskProgressResponse.ProtoReflect.Descriptor instead.
func (*ReportTaskProgressResponse) Descriptor() ([]byte, []int) {
	return file_api_api_proto_rawDescGZIP(), []int{9}
}

func (x *ReportTaskProgressResponse) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

func (x *ReportTaskProgressResponse) GetBaseResp() *base.BaseResp {
	if x != nil {
		return x.BaseResp
	}
	return nil
}

type DispatchTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *golem.Task            `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DispatchTaskRequest) Reset() {
	*x = DispatchTaskRequest{}
	mi := &file_api_api_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DispatchTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DispatchTaskRequest) ProtoMessage() {}

func (x *DispatchTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DispatchTaskRequest.ProtoReflect.Descriptor instead.
func (*DispatchTaskRequest) Descriptor() ([]byte, []int) {
	return file_api_api_proto_rawDescGZIP(), []int{10}
}

func (x *DispatchTaskRequest) GetTask() *golem.Task {
	if x != nil {
		return x.Task
	}
	return nil
}

type DispatchTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	RejectReason  string                 `protobuf:"bytes,2,opt,name=reject_reason,json=rejectReason,proto3" json:"reject_reason,omitempty"`
	BaseResp      *base.BaseResp         `protobuf:"bytes,255,opt,name=base_resp,json=baseResp,proto3" json:"base_resp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DispatchTaskResponse) Reset() {
	*x = DispatchTaskResponse{}
	mi := &file_api_api_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DispatchTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DispatchTaskResponse) ProtoMessage() {}

func (x *DispatchTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DispatchTaskResponse.ProtoReflect.Descriptor instead.
func (*DispatchTaskResponse) Descriptor() ([]byte, []int) {
	return file_api_api_proto_rawDescGZIP(), []int{11}
}

func (x *DispatchTaskResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *DispatchTaskResponse) GetRejectReason() string {
	if x != nil {
		return x.RejectReason
	}
	return ""
}

func (x *DispatchTaskResponse) GetBaseResp() *base.BaseResp {
	if x != nil {
		return x.BaseResp
	}
	return nil
}

type CancelTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelTaskRequest) Reset() {
	*x = CancelTaskRequest{}
	mi := &file_api_api_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelTaskRequest) ProtoMessage() {}

func (x *CancelTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelTaskRequest.ProtoReflect.Descriptor instead.
func (*CancelTaskRequest) Descriptor() ([]byte, []int) {
	return file_api_api_proto_rawDescGZIP(), []int{12}
}

func (x *CancelTaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *CancelTaskRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type CancelTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	BaseResp      *base.BaseResp         `protobuf:"bytes,255,opt,name=base_resp,json=baseResp,proto3" json:"base_resp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelTaskResponse) Reset() {
	*x = CancelTaskResponse{}
	mi := &file_api_api_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelTaskResponse) ProtoMessage() {}

func (x *CancelTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelTaskResponse.ProtoReflect.Descriptor instead.
func (*CancelTaskResponse) Descriptor() ([]byte, []int) {
	return file_api_api_proto_rawDescGZIP(), []int{13}
}

func (x *CancelTaskResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CancelTaskResponse) GetBaseResp() *base.BaseResp {
	if x != nil {
		return x.BaseResp
	}
	return nil
}

type DrainNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DrainNodeRequest) Reset() {
	*x = DrainNodeRequest{}
	mi := &file_api_api_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DrainNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DrainNodeRequest) ProtoMessage() {}

func (x *DrainNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DrainNodeRequest.ProtoReflect.Descriptor instead.
func (*DrainNodeRequest) Descriptor() ([]byte, []int) {
	return file_api_api_proto_rawDescGZIP(), []int{14}
}

func (x *DrainNodeRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type DrainNodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	BaseResp      *base.BaseResp         `protobuf:"bytes,255,opt,name=base_resp,json=baseResp,proto3" json:"base_resp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DrainNodeResponse) Reset() {
	*x = DrainNodeResponse{}
	mi := &file_api_api_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DrainNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DrainNodeResponse) ProtoMessage() {}

func (x *DrainNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DrainNodeResponse.ProtoReflect.Descriptor instead.
func (*DrainNodeResponse) Descriptor() ([]byte, []int) {
	return file_api_api_proto_rawDescGZIP(), []int{15}
}

func (x *DrainNodeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DrainNodeResponse) GetBaseResp() *base.BaseResp {
	if x != nil {
		return x.BaseResp
	}
	return nil
}

type ListNodesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusFilter  golem.NodeStatus       `protobuf:"varint,1,opt,name=status_filter,json=statusFilter,proto3,enum=golem.NodeStatus" json:"status_filter,omitempty"` // 可选: 按状态过滤
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNodesRequest) Reset() {
	*x = ListNodesRequest{}
	mi := &file_api_api_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNodesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNodesRequest) ProtoMessage() {}

func (x *ListNodesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNodesRequest.ProtoReflect.Descriptor instead.
func (*ListNodesRequest) Descriptor() ([]byte, []int) {
	return file_api_api_proto_rawDescGZIP(), []int{16}
}

func (x *ListNodesRequest) GetStatusFilter() golem.NodeStatus {
	if x != nil {
		return x.StatusFilter
	}
	return golem.NodeStatus(0)
}

func (x *ListNodesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListNodesRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListNodesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         []*golem.NodeInfo      `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	TotalCount    int32                  `protobuf:"varint,3,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	BaseResp      *base.BaseResp         `protobuf:"bytes,255,opt,name=base_resp,json=baseResp,proto3" json:"base_resp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNodesResponse) Reset() {
	*x = ListNodesResponse{}
	mi := &file_api_api_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNodesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNodesResponse) ProtoMessage() {}

func (x *ListNodesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNodesResponse.ProtoReflect.Descriptor instead.
func (*ListNodesResponse) Descriptor() ([]byte, []int) {
	return file_api_api_proto_rawDescGZIP(), []int{17}
}

func (x *ListNodesResponse) GetNodes() []*golem.NodeInfo {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *ListNodesResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

func (x *ListNodesResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ListNodesResponse) GetBaseResp() *base.BaseResp {
	if x != nil {
		return x.BaseResp
	}
	return nil
}

type GetNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNodeRequest) Reset() {
	*x = GetNodeRequest{}
	mi := &file_api_api_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodeRequest) ProtoMessage() {}

func (x *GetNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNodeRequest.ProtoReflect.Descriptor instead.
func (*GetNodeRequest) Descriptor() ([]byte, []int) {
	return file_api_api_proto_rawDescGZIP(), []int{18}
}

func (x *GetNodeRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type GetNodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeInfo      *golem.NodeInfo        `protobuf:"bytes,1,opt,name=node_info,json=nodeInfo,proto3" json:"node_info,omitempty"`
	LoadInfo      *golem.NodeLoadInfo    `protobuf:"bytes,2,opt,name=load_info,json=loadInfo,proto3" json:"load_info,omitempty"`
	BaseResp      *base.BaseResp         `protobuf:"bytes,255,opt,name=base_resp,json=baseResp,proto3" json:"base_resp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNodeResponse) Reset() {
	*x = GetNodeResponse{}
	mi := &file_api_api_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodeResponse) ProtoMessage() {}

func (x *GetNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNodeResponse.ProtoReflect.Descriptor instead.
func (*GetNodeResponse) Descriptor() ([]byte, []int) {
	return file_api_api_proto_rawDescGZIP(), []int{19}
}

func (x *GetNodeResponse) GetNodeInfo() *golem.NodeInfo {
	if x != nil {
		return x.NodeInfo
	}
	return nil
}

func (x *GetNodeResponse) GetLoadInfo() *golem.NodeLoadInfo {
	if x != nil {
		return x.LoadInfo
	}
	return nil
}

func (x *GetNodeResponse) GetBaseResp() *base.BaseResp {
	if x != nil {
		return x.BaseResp
	}
	return nil
}

type CordonNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CordonNodeRequest) Reset() {
	*x = CordonNodeRequest{}
	mi := &file_api_api_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CordonNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CordonNodeRequest) ProtoMessage() {}

func (x *CordonNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CordonNodeRequest.ProtoReflect.Descriptor instead.
func (*CordonNodeRequest) Descriptor() ([]byte, []int) {
	return file_api_api_proto_rawDescGZIP(), []int{20}
}

func (x *CordonNodeRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *CordonNodeRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type CordonNodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	BaseResp      *base.BaseResp         `protobuf:"bytes,255,opt,name=base_resp,json=baseResp,proto3" json:"base_resp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CordonNodeResponse) Reset() {
	*x = CordonNodeResponse{}
	mi := &file_api_api_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CordonNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CordonNodeResponse) ProtoMessage() {}

func (x *CordonNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CordonNodeResponse.ProtoReflect.Descriptor instead.
func (*CordonNodeResponse) Descriptor() ([]byte, []int) {
	return file_api_api_proto_rawDescGZIP(), []int{21}
}

func (x *CordonNodeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CordonNodeResponse) GetBaseResp() *base.BaseResp {
	if x != nil {
		return x.BaseResp
	}
	return nil
}

type UncordonNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UncordonNodeRequest) Reset() {
	*x = UncordonNodeRequest{}
	mi := &file_api_api_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UncordonNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UncordonNodeRequest) ProtoMessage() {}

func (x *UncordonNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UncordonNodeRequest.ProtoReflect.Descriptor instead.
func (*UncordonNodeRequest) Descriptor() ([]byte, []int) {
	return file_api_api_proto_rawDescGZIP(), []int{22}
}

func (x *UncordonNodeRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type UncordonNodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	BaseResp      *base.BaseResp         `protobuf:"bytes,255,opt,name=base_resp,json=baseResp,proto3" json:"base_resp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UncordonNodeResponse) Reset() {
	*x = UncordonNodeResponse{}
	mi := &file_api_api_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UncordonNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UncordonNodeResponse) ProtoMessage() {}

func (x *UncordonNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UncordonNodeResponse.ProtoReflect.Descriptor instead.
func (*UncordonNodeResponse) Descriptor() ([]byte, []int) {
	return file_api_api_proto_rawDescGZIP(), []int{23}
}

func (x *UncordonNodeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UncordonNodeResponse) GetBaseResp() *base.BaseResp {
	if x != nil {
		return x.BaseResp
	}
	return nil
}

var File_api_api_proto protoreflect.FileDescriptor

const file_api_api_proto_rawDesc = "" +
	"\n" +
	"\rapi/api.proto\x12\x03api\x1a\x0fbase/base.proto\x1a\x11golem/golem.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x90\x01\n" +
	"\x0fRegisterRequest\x12\x1d\n" +
	"\n" +
	"join_token\x18\x01 \x01(\tR\tjoinToken\x12,\n" +
	"\tnode_info\x18\x02 \x01(\v2\x0f.golem.NodeInfoR\bnodeInfo\x120\n" +
	"\tload_info\x18\x03 \x01(\v2\x13.golem.NodeLoadInfoR\bloadInfo\"\x9a\x01\n" +
	"\x10RegisterResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\x12#\n" +
	"\rreject_reason\x18\x03 \x01(\tR\frejectReason\x12,\n" +
	"\tbase_resp\x18\xff\x01 \x01(\v2\x0e.base.BaseRespR\bbaseResp\"\x97\x01\n" +
	"\x10HeartbeatRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x120\n" +
	"\tload_info\x18\x02 \x01(\v2\x13.golem.NodeLoadInfoR\bloadInfo\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"e\n" +
	"\x11HeartbeatResponse\x12\"\n" +
	"\facknowledged\x18\x01 \x01(\bR\facknowledged\x12,\n" +
	"\x06action\x18\x02 \x01(\x0e2\x14.api.HeartbeatActionR\x06action\"D\n" +
	"\x11DeregisterRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"\\\n" +
	"\x12DeregisterResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12,\n" +
	"\tbase_resp\x18\xff\x01 \x01(\v2\x0e.base.BaseRespR\bbaseResp\"f\n" +
	"\x17ReportTaskResultRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x122\n" +
	"\vtask_result\x18\x02 \x01(\v2\x11.golem.TaskResultR\n" +
	"taskResult\"l\n" +
	"\x18ReportTaskResultResponse\x12\"\n" +
	"\facknowledged\x18\x01 \x01(\bR\facknowledged\x12,\n" +
	"\tbase_resp\x18\xff\x01 \x01(\v2\x0e.base.BaseRespR\bbaseResp\"n\n" +
	"\x19ReportTaskProgressRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x128\n" +
	"\rtask_progress\x18\x02 \x01(\v2\x13.golem.TaskProgressR\ftaskProgress\"n\n" +
	"\x1aReportTaskProgressResponse\x12\"\n" +
	"\facknowledged\x18\x01 \x01(\bR\facknowledged\x12,\n" +
	"\tbase_resp\x18\xff\x01 \x01(\v2\x0e.base.BaseRespR\bbaseResp\"6\n" +
	"\x13DispatchTaskRequest\x12\x1f\n" +
	"\x04task\x18\x01 \x01(\v2\v.golem.TaskR\x04task\"\x85\x01\n" +
	"\x14DispatchTaskResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12#\n" +
	"\rreject_reason\x18\x02 \x01(\tR\frejectReason\x12,\n" +
	"\tbase_resp\x18\xff\x01 \x01(\v2\x0e.base.BaseRespR\bbaseResp\"D\n" +
	"\x11CancelTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"\\\n" +
	"\x12CancelTaskResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12,\n" +
	"\tbase_resp\x18\xff\x01 \x01(\v2\x0e.base.BaseRespR\bbaseResp\"+\n" +
	"\x10DrainNodeRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\"[\n" +
	"\x11DrainNodeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12,\n" +
	"\tbase_resp\x18\xff\x01 \x01(\v2\x0e.base.BaseRespR\bbaseResp\"\x86\x01\n" +
	"\x10ListNodesRequest\x126\n" +
	"\rstatus_filter\x18\x01 \x01(\x0e2\x11.golem.NodeStatusR\fstatusFilter\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageToken\"\xb1\x01\n" +
	"\x11ListNodesResponse\x12%\n" +
	"\x05nodes\x18\x01 \x03(\v2\x0f.golem.NodeInfoR\x05nodes\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\x12\x1f\n" +
	"\vtotal_count\x18\x03 \x01(\x05R\n" +
	"totalCount\x12,\n" +
	"\tbase_resp\x18\xff\x01 \x01(\v2\x0e.base.BaseRespR\bbaseResp\")\n" +
	"\x0eGetNodeRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\"\x9f\x01\n" +
	"\x0fGetNodeResponse\x12,\n" +
	"\tnode_info\x18\x01 \x01(\v2\x0f.golem.NodeInfoR\bnodeInfo\x120\n" +
	"\tload_info\x18\x02 \x01(\v2\x13.golem.NodeLoadInfoR\bloadInfo\x12,\n" +
	"\tbase_resp\x18\xff\x01 \x01(\v2\x0e.base.BaseRespR\bbaseResp\"D\n" +
	"\x11CordonNodeRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"\\\n" +
	"\x12CordonNodeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12,\n" +
	"\tbase_resp\x18\xff\x01 \x01(\v2\x0e.base.BaseRespR\bbaseResp\".\n" +
	"\x13UncordonNodeRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\"^\n" +
	"\x14UncordonNodeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12,\n" +
	"\tbase_resp\x18\xff\x01 \x01(\v2\x0e.base.BaseRespR\bbaseResp*\x89\x01\n" +
	"\x0fHeartbeatAction\x12 \n" +
	"\x1cHEARTBEAT_ACTION_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15HEARTBEAT_ACTION_NONE\x10\x01\x12\x1a\n" +
	"\x16HEARTBEAT_ACTION_DRAIN\x10\x02\x12\x1d\n" +
	"\x19HEARTBEAT_ACTION_SHUTDOWN\x10\x032\xf2\x02\n" +
	"\x10GolemNodeService\x127\n" +
	"\bRegister\x12\x14.api.RegisterRequest\x1a\x15.api.RegisterResponse\x12>\n" +
	"\tHeartbeat\x12\x15.api.HeartbeatRequest\x1a\x16.api.HeartbeatResponse(\x010\x01\x12=\n" +
	"\n" +
	"Deregister\x12\x16.api.DeregisterRequest\x1a\x17.api.DeregisterResponse\x12O\n" +
	"\x10ReportTaskResult\x12\x1c.api.ReportTaskResultRequest\x1a\x1d.api.ReportTaskResultResponse\x12U\n" +
	"\x12ReportTaskProgress\x12\x1e.api.ReportTaskProgressRequest\x1a\x1f.api.ReportTaskProgressResponse2\xd8\x01\n" +
	"\x16HivemindControlService\x12C\n" +
	"\fDispatchTask\x12\x18.api.DispatchTaskRequest\x1a\x19.api.DispatchTaskResponse\x12=\n" +
	"\n" +
	"CancelTask\x12\x16.api.CancelTaskRequest\x1a\x17.api.CancelTaskResponse\x12:\n" +
	"\tDrainNode\x12\x15.api.DrainNodeRequest\x1a\x16.api.DrainNodeResponse2\x8c\x02\n" +
	"\x14HivemindAdminService\x12:\n" +
	"\tListNodes\x12\x15.api.ListNodesRequest\x1a\x16.api.ListNodesResponse\x124\n" +
	"\aGetNode\x12\x13.api.GetNodeRequest\x1a\x14.api.GetNodeResponse\x12=\n" +
	"\n" +
	"CordonNode\x12\x16.api.CordonNodeRequest\x1a\x17.api.CordonNodeResponse\x12C\n" +
	"\fUncordonNode\x12\x18.api.UncordonNodeRequest\x1a\x19.api.UncordonNodeResponseB+Z)github.com/kiosk404/echoryn/pkg/proto/apib\x06proto3"

var (
	file_api_api_proto_rawDescOnce sync.Once
	file_api_api_proto_rawDescData []byte
)

func file_api_api_proto_rawDescGZIP() []byte {
	file_api_api_proto_rawDescOnce.Do(func() {
		file_api_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_api_proto_rawDesc), len(file_api_api_proto_rawDesc)))
	})
	return file_api_api_proto_rawDescData
}

var file_api_api_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_api_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_api_api_proto_goTypes = []any{
	(HeartbeatAction)(0),               // 0: api.HeartbeatAction
	(*RegisterRequest)(nil),            // 1: api.RegisterRequest
	(*RegisterResponse)(nil),           // 2: api.RegisterResponse
	(*HeartbeatRequest)(nil),           // 3: api.HeartbeatRequest
	(*HeartbeatResponse)(nil),          // 4: api.HeartbeatResponse
	(*DeregisterRequest)(nil),          // 5: api.DeregisterRequest
	(*DeregisterResponse)(nil),         // 6: api.DeregisterResponse
	(*ReportTaskResultRequest)(nil),    // 7: api.ReportTaskResultRequest
	(*ReportTaskResultResponse)(nil),   // 8: api.ReportTaskResultResponse
	(*ReportTaskProgressRequest)(nil),  // 9: api.ReportTaskProgressRequest
	(*ReportTaskProgressResponse)(nil), // 10: api.ReportTaskProgressResponse
	(*DispatchTaskRequest)(nil),        // 11: api.DispatchTaskRequest
	(*DispatchTaskResponse)(nil),       // 12: api.DispatchTaskResponse
	(*CancelTaskRequest)(nil),          // 13: api.CancelTaskRequest
	(*CancelTaskResponse)(nil),         // 14: api.CancelTaskResponse
	(*DrainNodeRequest)(nil),           // 15: api.DrainNodeRequest
	(*DrainNodeResponse)(nil),          // 16: api.DrainNodeResponse
	(*ListNodesRequest)(nil),           // 17: api.ListNodesRequest
	(*ListNodesResponse)(nil),          // 18: api.ListNodesResponse
	(*GetNodeRequest)(nil),             // 19: api.GetNodeRequest
	(*GetNodeResponse)(nil),            // 20: api.GetNodeResponse
	(*CordonNodeRequest)(nil),          // 21: api.CordonNodeRequest
	(*CordonNodeResponse)(nil),         // 22: api.CordonNodeResponse
	(*UncordonNodeRequest)(nil),        // 23: api.UncordonNodeRequest
	(*UncordonNodeResponse)(nil),       // 24: api.UncordonNodeResponse
	(*golem.NodeInfo)(nil),             // 25: golem.NodeInfo
	(*golem.NodeLoadInfo)(nil),         // 26: golem.NodeLoadInfo
	(*base.BaseResp)(nil),              // 27: base.BaseResp
	(*timestamppb.Timestamp)(nil),      // 28: google.protobuf.Timestamp
	(*golem.TaskResult)(nil),           // 29: golem.TaskResult
	(*golem.TaskProgress)(nil),         // 30: golem.TaskProgress
	(*golem.Task)(nil),                 // 31: golem.Task
	(golem.NodeStatus)(0),              // 32: golem.NodeStatus
}
var file_api_api_proto_depIdxs = []int32{
	25, // 0: api.RegisterRequest.node_info:type_name -> golem.NodeInfo
	26, // 1: api.RegisterRequest.load_info:type_name -> golem.NodeLoadInfo
	27, // 2: api.RegisterResponse.base_resp:type_name -> base.BaseResp
	26, // 3: api.HeartbeatRequest.load_info:type_name -> golem.NodeLoadInfo
	28, // 4: api.HeartbeatRequest.timestamp:type_name -> google.protobuf.Timestamp
	0,  // 5: api.HeartbeatResponse.action:type_name -> api.HeartbeatAction
	27, // 6: api.DeregisterResponse.base_resp:type_name -> base.BaseResp
	29, // 7: api.ReportTaskResultRequest.task_result:type_name -> golem.TaskResult
	27, // 8: api.ReportTaskResultResponse.base_resp:type_name -> base.BaseResp
	30, // 9: api.ReportTaskProgressRequest.task_progress:type_name -> golem.TaskProgress
	27, // 10: api.ReportTaskProgressResponse.base_resp:type_name -> base.BaseResp
	31, // 11: api.DispatchTaskRequest.task:type_name -> golem.Task
	27, // 12: api.DispatchTaskResponse.base_resp:type_name -> base.BaseResp
	27, // 13: api.CancelTaskResponse.base_resp:type_name -> base.BaseResp
	27, // 14: api.DrainNodeResponse.base_resp:type_name -> base.BaseResp
	32, // 15: api.ListNodesRequest.status_filter:type_name -> golem.NodeStatus
	25, // 16: api.ListNodesResponse.nodes:type_name -> golem.NodeInfo
	27, // 17: api.ListNodesResponse.base_resp:type_name -> base.BaseResp
	25, // 18: api.GetNodeResponse.node_info:type_name -> golem.NodeInfo
	26, // 19: api.GetNodeResponse.load_info:type_name -> golem.NodeLoadInfo
	27, // 20: api.GetNodeResponse.base_resp:type_name -> base.BaseResp
	27, // 21: api.CordonNodeResponse.base_resp:type_name -> base.BaseResp
	27, // 22: api.UncordonNodeResponse.base_resp:type_name -> base.BaseResp
	1,  // 23: api.GolemNodeService.Register:input_type -> api.RegisterRequest
	3,  // 24: api.GolemNodeService.Heartbeat:input_type -> api.HeartbeatRequest
	5,  // 25: api.GolemNodeService.Deregister:input_type -> api.DeregisterRequest
	7,  // 26: api.GolemNodeService.ReportTaskResult:input_type -> api.ReportTaskResultRequest
	9,  // 27: api.GolemNodeService.ReportTaskProgress:input_type -> api.ReportTaskProgressRequest
	11, // 28: api.HivemindControlService.DispatchTask:input_type -> api.DispatchTaskRequest
	13, // 29: api.HivemindControlService.CancelTask:input_type -> api.CancelTaskRequest
	15, // 30: api.HivemindControlService.DrainNode:input_type -> api.DrainNodeRequest
	17, // 31: api.HivemindAdminService.ListNodes:input_type -> api.ListNodesRequest
	19, // 32: api.HivemindAdminService.GetNode:input_type -> api.GetNodeRequest
	21, // 33: api.HivemindAdminService.CordonNode:input_type -> api.CordonNodeRequest
	23, // 34: api.HivemindAdminService.UncordonNode:input_type -> api.UncordonNodeRequest
	2,  // 35: api.GolemNodeService.Register:output_type -> api.RegisterResponse
	4,  // 36: api.GolemNodeService.Heartbeat:output_type -> api.HeartbeatResponse
	6,  // 37: api.GolemNodeService.Deregister:output_type -> api.DeregisterResponse
	8,  // 38: api.GolemNodeService.ReportTaskResult:output_type -> api.ReportTaskResultResponse
	10, // 39: api.GolemNodeService.ReportTaskProgress:output_type -> api.ReportTaskProgressResponse
	12, // 40: api.HivemindControlService.DispatchTask:output_type -> api.DispatchTaskResponse
	14, // 41: api.HivemindControlService.CancelTask:output_type -> api.CancelTaskResponse
	16, // 42: api.HivemindControlService.DrainNode:output_type -> api.DrainNodeResponse
	18, // 43: api.HivemindAdminService.ListNodes:output_type -> api.ListNodesResponse
	20, // 44: api.HivemindAdminService.GetNode:output_type -> api.GetNodeResponse
	22, // 45: api.HivemindAdminService.CordonNode:output_type -> api.CordonNodeResponse
	24, // 46: api.HivemindAdminService.UncordonNode:output_type -> api.UncordonNodeResponse
	35, // [35:47] is the sub-list for method output_type
	23, // [23:35] is the sub-list for method input_type
	23, // [23:23] is the sub-list for extension type_name
	23, // [23:23] is the sub-list for extension extendee
	0,  // [0:23] is the sub-list for field type_name
}

func init() { file_api_api_proto_init() }
func file_api_api_proto_init() {
	if File_api_api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_api_proto_rawDesc), len(file_api_api_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_api_api_proto_goTypes,
		DependencyIndexes: file_api_api_proto_depIdxs,
		EnumInfos:         file_api_api_proto_enumTypes,
		MessageInfos:      file_api_api_proto_msgTypes,
	}.Build()
	File_api_api_proto = out.File
	file_api_api_proto_goTypes = nil
	file_api_api_proto_depIdxs = nil
}
