// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: api/api.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GolemNodeService_Register_FullMethodName           = "/api.GolemNodeService/Register"
	GolemNodeService_Heartbeat_FullMethodName          = "/api.GolemNodeService/Heartbeat"
	GolemNodeService_Deregister_FullMethodName         = "/api.GolemNodeService/Deregister"
	GolemNodeService_ReportTaskResult_FullMethodName   = "/api.GolemNodeService/ReportTaskResult"
	GolemNodeService_ReportTaskProgress_FullMethodName = "/api.GolemNodeService/ReportTaskProgress"
)

// GolemNodeServiceClient is the client API for GolemNodeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ==========================================================================
// GolemNodeService — Golem 节点向 Hivemind 注册 / 心跳 / 上报结果
// 由 Golem 调用, Hivemind 作为 gRPC Server 端
// ==========================================================================
type GolemNodeServiceClient interface {
	// Register 注册 Golem 节点到 Hivemind
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
	// Heartbeat 双向流: Golem 定期上报负载, Hivemind 可下发控制指令
	Heartbeat(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[HeartbeatRequest, HeartbeatResponse], error)
	// Deregister 节点主动注销 (graceful shutdown)
	Deregister(ctx context.Context, in *DeregisterRequest, opts ...grpc.CallOption) (*DeregisterResponse, error)
	// ReportTaskResult 上报任务执行结果
	ReportTaskResult(ctx context.Context, in *ReportTaskResultRequest, opts ...grpc.CallOption) (*ReportTaskResultResponse, error)
	// ReportTaskProgress 上报任务执行进度
	ReportTaskProgress(ctx context.Context, in *ReportTaskProgressRequest, opts ...grpc.CallOption) (*ReportTaskProgressResponse, error)
}

type golemNodeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGolemNodeServiceClient(cc grpc.ClientConnInterface) GolemNodeServiceClient {
	return &golemNodeServiceClient{cc}
}

func (c *golemNodeServiceClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, GolemNodeService_Register_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *golemNodeServiceClient) Heartbeat(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[HeartbeatRequest, HeartbeatResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &GolemNodeService_ServiceDesc.Streams[0], GolemNodeService_Heartbeat_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[HeartbeatRequest, HeartbeatResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GolemNodeService_HeartbeatClient = grpc.BidiStreamingClient[HeartbeatRequest, HeartbeatResponse]

func (c *golemNodeServiceClient) Deregister(ctx context.Context, in *DeregisterRequest, opts ...grpc.CallOption) (*DeregisterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeregisterResponse)
	err := c.cc.Invoke(ctx, GolemNodeService_Deregister_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *golemNodeServiceClient) ReportTaskResult(ctx context.Context, in *ReportTaskResultRequest, opts ...grpc.CallOption) (*ReportTaskResultResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportTaskResultResponse)
	err := c.cc.Invoke(ctx, GolemNodeService_ReportTaskResult_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *golemNodeServiceClient) ReportTaskProgress(ctx context.Context, in *ReportTaskProgressRequest, opts ...grpc.CallOption) (*ReportTaskProgressResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportTaskProgressResponse)
	err := c.cc.Invoke(ctx, GolemNodeService_ReportTaskProgress_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GolemNodeServiceServer is the server API for GolemNodeService service.
// All implementations must embed UnimplementedGolemNodeServiceServer
// for forward compatibility.
//
// ==========================================================================
// GolemNodeService — Golem 节点向 Hivemind 注册 / 心跳 / 上报结果
// 由 Golem 调用, Hivemind 作为 gRPC Server 端
// ==========================================================================
type GolemNodeServiceServer interface {
	// Register 注册 Golem 节点到 Hivemind
	Register(context.Context, *RegisterRequest) (*RegisterResponse, error)
	// Heartbeat 双向流: Golem 定期上报负载, Hivemind 可下发控制指令
	Heartbeat(grpc.BidiStreamingServer[HeartbeatRequest, HeartbeatResponse]) error
	// Deregister 节点主动注销 (graceful shutdown)
	Deregister(context.Context, *DeregisterRequest) (*DeregisterResponse, error)
	// ReportTaskResult 上报任务执行结果
	ReportTaskResult(context.Context, *ReportTaskResultRequest) (*ReportTaskResultResponse, error)
	// ReportTaskProgress 上报任务执行进度
	ReportTaskProgress(context.Context, *ReportTaskProgressRequest) (*ReportTaskProgressResponse, error)
	mustEmbedUnimplementedGolemNodeServiceServer()
}

// UnimplementedGolemNodeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGolemNodeServiceServer struct{}

func (UnimplementedGolemNodeServiceServer) Register(context.Context, *RegisterRequest) (*RegisterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedGolemNodeServiceServer) Heartbeat(grpc.BidiStreamingServer[HeartbeatRequest, HeartbeatResponse]) error {
	return status.Error(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedGolemNodeServiceServer) Deregister(context.Context, *DeregisterRequest) (*DeregisterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Deregister not implemented")
}
func (UnimplementedGolemNodeServiceServer) ReportTaskResult(context.Context, *ReportTaskResultRequest) (*ReportTaskResultResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportTaskResult not implemented")
}
func (UnimplementedGolemNodeServiceServer) ReportTaskProgress(context.Context, *ReportTaskProgressRequest) (*ReportTaskProgressResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportTaskProgress not implemented")
}
func (UnimplementedGolemNodeServiceServer) mustEmbedUnimplementedGolemNodeServiceServer() {}
func (UnimplementedGolemNodeServiceServer) testEmbeddedByValue()                          {}

// UnsafeGolemNodeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GolemNodeServiceServer will
// result in compilation errors.
type UnsafeGolemNodeServiceServer interface {
	mustEmbedUnimplementedGolemNodeServiceServer()
}

func RegisterGolemNodeServiceServer(s grpc.ServiceRegistrar, srv GolemNodeServiceServer) {
	// If the following call panics, it indicates UnimplementedGolemNodeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GolemNodeService_ServiceDesc, srv)
}

func _GolemNodeService_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GolemNodeServiceServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GolemNodeService_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GolemNodeServiceServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GolemNodeService_Heartbeat_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GolemNodeServiceServer).Heartbeat(&grpc.GenericServerStream[HeartbeatRequest, HeartbeatResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GolemNodeService_HeartbeatServer = grpc.BidiStreamingServer[HeartbeatRequest, HeartbeatResponse]

func _GolemNodeService_Deregister_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeregisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GolemNodeServiceServer).Deregister(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GolemNodeService_Deregister_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GolemNodeServiceServer).Deregister(ctx, req.(*DeregisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GolemNodeService_ReportTaskResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportTaskResultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GolemNodeServiceServer).ReportTaskResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GolemNodeService_ReportTaskResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GolemNodeServiceServer).ReportTaskResult(ctx, req.(*ReportTaskResultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GolemNodeService_ReportTaskProgress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportTaskProgressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GolemNodeServiceServer).ReportTaskProgress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GolemNodeService_ReportTaskProgress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GolemNodeServiceServer).ReportTaskProgress(ctx, req.(*ReportTaskProgressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GolemNodeService_ServiceDesc is the grpc.ServiceDesc for GolemNodeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GolemNodeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.GolemNodeService",
	HandlerType: (*GolemNodeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _GolemNodeService_Register_Handler,
		},
		{
			MethodName: "Deregister",
			Handler:    _GolemNodeService_Deregister_Handler,
		},
		{
			MethodName: "ReportTaskResult",
			Handler:    _GolemNodeService_ReportTaskResult_Handler,
		},
		{
			MethodName: "ReportTaskProgress",
			Handler:    _GolemNodeService_ReportTaskProgress_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Heartbeat",
			Handler:       _GolemNodeService_Heartbeat_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "api/api.proto",
}

const (
	HivemindControlService_DispatchTask_FullMethodName = "/api.HivemindControlService/DispatchTask"
	HivemindControlService_CancelTask_FullMethodName   = "/api.HivemindControlService/CancelTask"
	HivemindControlService_DrainNode_FullMethodName    = "/api.HivemindControlService/DrainNode"
)

// HivemindControlServiceClient is the client API for HivemindControlService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ==========================================================================
// HivemindControlService — Hivemind 向 Golem 下发任务和管控指令
// 由 Hivemind 调用, Golem 作为 gRPC Server 端 (或通过双向流实现)
// ==========================================================================
type HivemindControlServiceClient interface {
	// DispatchTask 下发任务到 Golem 节点
	DispatchTask(ctx context.Context, in *DispatchTaskRequest, opts ...grpc.CallOption) (*DispatchTaskResponse, error)
	// CancelTask 取消正在执行的任务
	CancelTask(ctx context.Context, in *CancelTaskRequest, opts ...grpc.CallOption) (*CancelTaskResponse, error)
	// DrainNode 排水节点 (停止接受新任务, 等待现有任务完成)
	DrainNode(ctx context.Context, in *DrainNodeRequest, opts ...grpc.CallOption) (*DrainNodeResponse, error)
}

type hivemindControlServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHivemindControlServiceClient(cc grpc.ClientConnInterface) HivemindControlServiceClient {
	return &hivemindControlServiceClient{cc}
}

func (c *hivemindControlServiceClient) DispatchTask(ctx context.Context, in *DispatchTaskRequest, opts ...grpc.CallOption) (*DispatchTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DispatchTaskResponse)
	err := c.cc.Invoke(ctx, HivemindControlService_DispatchTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hivemindControlServiceClient) CancelTask(ctx context.Context, in *CancelTaskRequest, opts ...grpc.CallOption) (*CancelTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelTaskResponse)
	err := c.cc.Invoke(ctx, HivemindControlService_CancelTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hivemindControlServiceClient) DrainNode(ctx context.Context, in *DrainNodeRequest, opts ...grpc.CallOption) (*DrainNodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DrainNodeResponse)
	err := c.cc.Invoke(ctx, HivemindControlService_DrainNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HivemindControlServiceServer is the server API for HivemindControlService service.
// All implementations must embed UnimplementedHivemindControlServiceServer
// for forward compatibility.
//
// ==========================================================================
// HivemindControlService — Hivemind 向 Golem 下发任务和管控指令
// 由 Hivemind 调用, Golem 作为 gRPC Server 端 (或通过双向流实现)
// ==========================================================================
type HivemindControlServiceServer interface {
	// DispatchTask 下发任务到 Golem 节点
	DispatchTask(context.Context, *DispatchTaskRequest) (*DispatchTaskResponse, error)
	// CancelTask 取消正在执行的任务
	CancelTask(context.Context, *CancelTaskRequest) (*CancelTaskResponse, error)
	// DrainNode 排水节点 (停止接受新任务, 等待现有任务完成)
	DrainNode(context.Context, *DrainNodeRequest) (*DrainNodeResponse, error)
	mustEmbedUnimplementedHivemindControlServiceServer()
}

// UnimplementedHivemindControlServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHivemindControlServiceServer struct{}

func (UnimplementedHivemindControlServiceServer) DispatchTask(context.Context, *DispatchTaskRequest) (*DispatchTaskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DispatchTask not implemented")
}
func (UnimplementedHivemindControlServiceServer) CancelTask(context.Context, *CancelTaskRequest) (*CancelTaskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelTask not implemented")
}
func (UnimplementedHivemindControlServiceServer) DrainNode(context.Context, *DrainNodeRequest) (*DrainNodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DrainNode not implemented")
}
func (UnimplementedHivemindControlServiceServer) mustEmbedUnimplementedHivemindControlServiceServer() {
}
func (UnimplementedHivemindControlServiceServer) testEmbeddedByValue() {}

// UnsafeHivemindControlServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HivemindControlServiceServer will
// result in compilation errors.
type UnsafeHivemindControlServiceServer interface {
	mustEmbedUnimplementedHivemindControlServiceServer()
}

func RegisterHivemindControlServiceServer(s grpc.ServiceRegistrar, srv HivemindControlServiceServer) {
	// If the following call panics, it indicates UnimplementedHivemindControlServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HivemindControlService_ServiceDesc, srv)
}

func _HivemindControlService_DispatchTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DispatchTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HivemindControlServiceServer).DispatchTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HivemindControlService_DispatchTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HivemindControlServiceServer).DispatchTask(ctx, req.(*DispatchTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HivemindControlService_CancelTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HivemindControlServiceServer).CancelTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HivemindControlService_CancelTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HivemindControlServiceServer).CancelTask(ctx, req.(*CancelTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HivemindControlService_DrainNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DrainNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HivemindControlServiceServer).DrainNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HivemindControlService_DrainNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HivemindControlServiceServer).DrainNode(ctx, req.(*DrainNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HivemindControlService_ServiceDesc is the grpc.ServiceDesc for HivemindControlService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HivemindControlService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.HivemindControlService",
	HandlerType: (*HivemindControlServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DispatchTask",
			Handler:    _HivemindControlService_DispatchTask_Handler,
		},
		{
			MethodName: "CancelTask",
			Handler:    _HivemindControlService_CancelTask_Handler,
		},
		{
			MethodName: "DrainNode",
			Handler:    _HivemindControlService_DrainNode_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/api.proto",
}

const (
	HivemindAdminService_ListNodes_FullMethodName    = "/api.HivemindAdminService/ListNodes"
	HivemindAdminService_GetNode_FullMethodName      = "/api.HivemindAdminService/GetNode"
	HivemindAdminService_CordonNode_FullMethodName   = "/api.HivemindAdminService/CordonNode"
	HivemindAdminService_UncordonNode_FullMethodName = "/api.HivemindAdminService/UncordonNode"
)

// HivemindAdminServiceClient is the client API for HivemindAdminService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ==========================================================================
// HivemindAdminService — 管理面 API, 供 echoctl / echadm 使用
// ==========================================================================
type HivemindAdminServiceClient interface {
	// ListNodes 列出所有注册的 Golem 节点
	ListNodes(ctx context.Context, in *ListNodesRequest, opts ...grpc.CallOption) (*ListNodesResponse, error)
	// GetNode 获取指定节点详情
	GetNode(ctx context.Context, in *GetNodeRequest, opts ...grpc.CallOption) (*GetNodeResponse, error)
	// CordonNode 隔离节点 (标记为不可调度)
	CordonNode(ctx context.Context, in *CordonNodeRequest, opts ...grpc.CallOption) (*CordonNodeResponse, error)
	// UncordonNode 取消节点隔离
	UncordonNode(ctx context.Context, in *UncordonNodeRequest, opts ...grpc.CallOption) (*UncordonNodeResponse, error)
}

type hivemindAdminServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHivemindAdminServiceClient(cc grpc.ClientConnInterface) HivemindAdminServiceClient {
	return &hivemindAdminServiceClient{cc}
}

func (c *hivemindAdminServiceClient) ListNodes(ctx context.Context, in *ListNodesRequest, opts ...grpc.CallOption) (*ListNodesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListNodesResponse)
	err := c.cc.Invoke(ctx, HivemindAdminService_ListNodes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hivemindAdminServiceClient) GetNode(ctx context.Context, in *GetNodeRequest, opts ...grpc.CallOption) (*GetNodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetNodeResponse)
	err := c.cc.Invoke(ctx, HivemindAdminService_GetNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hivemindAdminServiceClient) CordonNode(ctx context.Context, in *CordonNodeRequest, opts ...grpc.CallOption) (*CordonNodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CordonNodeResponse)
	err := c.cc.Invoke(ctx, HivemindAdminService_CordonNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hivemindAdminServiceClient) UncordonNode(ctx context.Context, in *UncordonNodeRequest, opts ...grpc.CallOption) (*UncordonNodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UncordonNodeResponse)
	err := c.cc.Invoke(ctx, HivemindAdminService_UncordonNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HivemindAdminServiceServer is the server API for HivemindAdminService service.
// All implementations must embed UnimplementedHivemindAdminServiceServer
// for forward compatibility.
//
// ==========================================================================
// HivemindAdminService — 管理面 API, 供 echoctl / echadm 使用
// ==========================================================================
type HivemindAdminServiceServer interface {
	// ListNodes 列出所有注册的 Golem 节点
	ListNodes(context.Context, *ListNodesRequest) (*ListNodesResponse, error)
	// GetNode 获取指定节点详情
	GetNode(context.Context, *GetNodeRequest) (*GetNodeResponse, error)
	// CordonNode 隔离节点 (标记为不可调度)
	CordonNode(context.Context, *CordonNodeRequest) (*CordonNodeResponse, error)
	// UncordonNode 取消节点隔离
	UncordonNode(context.Context, *UncordonNodeRequest) (*UncordonNodeResponse, error)
	mustEmbedUnimplementedHivemindAdminServiceServer()
}

// UnimplementedHivemindAdminServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHivemindAdminServiceServer struct{}

func (UnimplementedHivemindAdminServiceServer) ListNodes(context.Context, *ListNodesRequest) (*ListNodesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListNodes not implemented")
}
func (UnimplementedHivemindAdminServiceServer) GetNode(context.Context, *GetNodeRequest) (*GetNodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNode not implemented")
}
func (UnimplementedHivemindAdminServiceServer) CordonNode(context.Context, *CordonNodeRequest) (*CordonNodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CordonNode not implemented")
}
func (UnimplementedHivemindAdminServiceServer) UncordonNode(context.Context, *UncordonNodeRequest) (*UncordonNodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UncordonNode not implemented")
}
func (UnimplementedHivemindAdminServiceServer) mustEmbedUnimplementedHivemindAdminServiceServer() {}
func (UnimplementedHivemindAdminServiceServer) testEmbeddedByValue()                              {}

// UnsafeHivemindAdminServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HivemindAdminServiceServer will
// result in compilation errors.
type UnsafeHivemindAdminServiceServer interface {
	mustEmbedUnimplementedHivemindAdminServiceServer()
}

func RegisterHivemindAdminServiceServer(s grpc.ServiceRegistrar, srv HivemindAdminServiceServer) {
	// If the following call panics, it indicates UnimplementedHivemindAdminServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HivemindAdminService_ServiceDesc, srv)
}

func _HivemindAdminService_ListNodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListNodesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HivemindAdminServiceServer).ListNodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HivemindAdminService_ListNodes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HivemindAdminServiceServer).ListNodes(ctx, req.(*ListNodesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HivemindAdminService_GetNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HivemindAdminServiceServer).GetNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HivemindAdminService_GetNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HivemindAdminServiceServer).GetNode(ctx, req.(*GetNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HivemindAdminService_CordonNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CordonNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HivemindAdminServiceServer).CordonNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HivemindAdminService_CordonNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HivemindAdminServiceServer).CordonNode(ctx, req.(*CordonNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HivemindAdminService_UncordonNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UncordonNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HivemindAdminServiceServer).UncordonNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HivemindAdminService_UncordonNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HivemindAdminServiceServer).UncordonNode(ctx, req.(*UncordonNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HivemindAdminService_ServiceDesc is the grpc.ServiceDesc for HivemindAdminService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HivemindAdminService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.HivemindAdminService",
	HandlerType: (*HivemindAdminServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListNodes",
			Handler:    _HivemindAdminService_ListNodes_Handler,
		},
		{
			MethodName: "GetNode",
			Handler:    _HivemindAdminService_GetNode_Handler,
		},
		{
			MethodName: "CordonNode",
			Handler:    _HivemindAdminService_CordonNode_Handler,
		},
		{
			MethodName: "UncordonNode",
			Handler:    _HivemindAdminService_UncordonNode_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/api.proto",
}
